### ISSUE TITLE
mtls_endpoint_aliases not used as per RFC 8705 in PAR and token exchange

### ISSUE THREAD

**Issue by Aiden-Ziegelaar** [ConsumerDataRight/sandbox#12]
**Describe the bug**
Our infosec provider uses mTLS for the call to the token endpoint by default. This is supported through advertisement of the `mtls_endpoint_aliases` in the well known configuration. 

**To Reproduce**
1. Advertise `mtls_endpoint_aliases` in `{{INFOSEC_BASE_URL}}/.well-known/openid-configuration`in accordance with RFC 8705
```
{
    ...
    "mtls_endpoint_aliases": {
        "token_endpoint": "https://mtls.authncdr-test.energyaustralia.com.au/energyaustralia-cdr/oauth2/token",
        "revocation_endpoint": "https://mtls.authncdr-test.energyaustralia.com.au/energyaustralia-cdr/oauth2/revoke",
        "introspection_endpoint": "https://mtls.authncdr-test.energyaustralia.com.au/energyaustralia-cdr/oauth2/introspect",
        "pushed_authorization_request_endpoint": "https://mtls.authncdr-test.energyaustralia.com.au/energyaustralia-cdr/par"
    },
    ...
}
```
3. Construct request for consent and follow consent flow.
4. Call to token endpoint is made ignoring the `mtls_endpoint_aliases` and just extends the INFOSEC_BASE_URL or uses the top level parameter ( not sure what is actually happening in the background )

I don't have access to the flow logs to check but I suspect that this may also be occurring in the PAR flow where mTLS is being ignored.

**Expected behaviour**
`mtls_endpoint_aliases` should be used preferentially as per RFC 8705:
> An OAuth client intending to do mutual TLS (for OAuth client authentication and/or to acquire or use certificate-bound tokens) when making a request directly to the authorization server MUST use the alias URL of the endpoint within the mtls_endpoint_aliases, when present, in preference to the endpoint URL of the same name at the top level of metadata.

**Screenshots**
Not Applicable

**Additional context**
[RFC 8705](https://www.rfc-editor.org/rfc/rfc8705.html#name-metadata-for-mutual-tls-end)
[CDS Transaction Security](https://consumerdatastandardsaustralia.github.io/standards/#transaction-security)

**Comment by CDR-AndrewG** [comment]
Hi @Aiden-Ziegelaar, 

Thank you for getting in touch with us to raise this issue. The information provided and notification of the issue will greatly help to us make the sandbox more closely aligned with the CDR ecosystem.

We have logged the issue and will include a fix in a future release.

**Comment by Aiden-Ziegelaar** [comment]
Changes have been made by CE in a fork of the mock data recipient: 
https://github.com/cloudentity/mock-data-recipient

**Comment by Aiden-Ziegelaar** [comment]
I've added a PR providing the basic pattern we'd expect to use as a starting point:
https://github.com/ConsumerDataRight/mock-data-recipient/pull/55

**Comment by CDR-AndrewG** [comment]
Hi @Aiden-Ziegelaar,

This issue has now been resolved in the latest release of the Sandbox.
