### ISSUE TITLE
Final stage of PAR throws an error. 

### ISSUE THREAD

**Issue by Aiden-Ziegelaar** [ConsumerDataRight/sandbox#14]
**Describe the bug**
Final stage of PAR throws an error. On redirect back to `https://dr.cdrsandbox.gov.au/consent/callback` the request for the access token goes through, but then the next phase fails. 

**To Reproduce**
1. Initiate a PAR
2. Perform AuthN/AuthZ steps
3. Get Redirected back to data recipient

**Expected behaviour**
The expected behaviour is that the requested access token should be displayed to the end user and available in the 'Consumer Data Sharing' utilities. 

**Screenshots**
![Screen Shot 2022-10-26 at 11 15 53 am](https://user-images.githubusercontent.com/19164243/197926526-1a4009f3-3048-4cef-a891-83680be05664.png)

**Additional context**
I can see our infosec server exchanging the code for the access token, so it seems to be after that.

Directly after the call to get the access token there is a call to `https://consumerdatarightsandbox.b2clogin.com/consumerdatarightsandbox.onmicrosoft.com/b2c_1a_signup_signin/oauth2/v2.0/authorize` then to `https://dr.cdrsandbox.gov.au/signin-oidc` that gets redirected to the error page.

**Comment by CDR-AndrewG** [comment]
Hi @Aiden-Ziegelaar,

Thank you for raising this issue. We have identified what is causing the issue and are now working on a patch to address it.

**Comment by Aiden-Ziegelaar** [comment]
I'm still experiencing the same error with the new release.
Request ID: 00-79a502d6410972ce5f5234462f41ffc5-1e7db38647f87f0c-00

**Comment by CDR-AndrewG** [comment]
Hi @Aiden-Ziegelaar,

We have made a change that should resolve the issue. Can you please try again?

**Comment by Aiden-Ziegelaar** [comment]
Perfect, looks like that change has resolved the issue. I appreciate the speedy turnaround on the issue!

**Comment by CDR-AndrewG** [comment]
That's great to hear. Thank you for confirming. Please reach out if you encounter any other issues.
