### ISSUE TITLE
PUT DCR API

### ISSUE THREAD

**Issue by psharma211** [ConsumerDataRight/sandbox#16]
Recently for a softwareProductId after DCR for that particular softwareProductId, we added new redirect_uri through portal and updated. But with that redirect_uri it's failing in PAR call. We assume we need to do a PUT DCR call for the same clientID.

Can you help us withe the steps for PUT DCR call/updating clientId with new redirect_uri.

SoftwareProductId: d163b31d-affa-4e11-81c5-1196f615d33b
Currently we are following these steps: (but we are facing issue in step 1 itself)

1. Client credential token call.
     Details:
    curl -L -X POST 'https://dh-bank.secure.idp.cdrsandbox.gov.au/connect/token' -H 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=client_credentials' --data-urlencode 'client_id=71bc00e8-cfea-47b4-aaf3-4a0734bb094f' --data-urlencode 'scope=cdr-register:bank:read cdr-register:read' --data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' --data-urlencode 'client_assertion=eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiIsImtpZCI6IjE4NzI2MjQ5MzgzMTc3NzU4NjgxNzc2NTY0NjE4ODYxNTc1MzA2In0.eyJhdWQiOiJodHRwczovL3NlY3VyZS5hcGkuY2Ryc2FuZGJveC5nb3YuYXUvaWRwL2Nvbm5lY3QvdG9rZW4iLCJpc3MiOiI3MWJjMDBlOC1jZmVhLTQ3YjQtYWFmMy00YTA3MzRiYjA5NGYiLCJzdWIiOiI3MWJjMDBlOC1jZmVhLTQ3YjQtYWFmMy00YTA3MzRiYjA5NGYiLCJqdGkiOiIzZDc4M2U5ZS0wNmZlLTQ5NGYtOGQwOC1jYzNmMmNiN2NiYjQiLCJleHAiOjE2Njc5MTUwODgsImlhdCI6MTY2NzkxMTQ4OH0.TdEj0bYMY7jAtrL67I1zWSa5DYhM1iSDJ1QdbMsM-Dwj9x4-ry-TZpLAJQ3HCgdAC_lIILHjnS9-RUOKnfIO_gvAbW-UdtHBw-EfgBgz6Pp3KTCyLh_3whY-g6YNhbad60UemxSgufZtyRghXnjEU7mt5TMhGdiCn7SZWNVSot74CEoA9ecRBoILuxjY1wH6dNA7JrJswt5GAtVUy4HO1A0y_VA65FpZVwss2gpY-UNgbMHRDqnIJAxDFT9QiGBkJdk1snLcrE1UOZCNaqeUaOwtaFc_0a92Qg6pNGXKvwmzU4lko4LCrnijYz6x3I0ujOQYehZ854PCk_gnLKqjQQ'

Error: {invalid_client}
2. SSA call.
3. PUT DCR call.

Please let us know if you require any other additional information from our end.

**Comment by psharma211** [comment]
@CDR-DavidR can you please have look into it and help us on this request.

**Comment by CDR-AndrewG** [comment]
Hi @psharma211,

It looks like the token being used is for a different software product. The token belongs to client_id 3138713a-edb5-40fb-969e-09cd5e5f0bd9 which looks like one of your other Software Products.

This is the error I'm seeing in the data holder for your software product- "71bc00e8-cfea-47b4-aaf3-4a0734bb094f" tries to refresh token belonging to "3138713a-edb5-40fb-969e-09cd5e5f0bd9"

Can you confirm you are using a token generated for client_id 71bc00e8-cfea-47b4-aaf3-4a0734bb094f? If the error still occurs, let me know what time it happened to help me with finding the log entry.

**Comment by psharma211** [comment]
Hi @CDR-DavidR
[sb-logfile-20221111-055839.csv](https://github.com/ConsumerDataRight/sandbox/files/9986890/sb-logfile-20221111-055839.csv)
,

We are using client assertion jwt with the client id- 71bc00e8-cfea-47b4-aaf3-4a0734bb094f. Attaching sandbox portal logs for reference/further debugging.

Timestamp: Fri, 11 Nov 2022 05:50:30 GMT

**Comment by psharma211** [comment]
@CDR-DavidR can you please review and help on this

**Comment by CDR-DF** [comment]
Hi @psharma211,

The scopes being used at the data holder's token endpoint don't look correct.  For DCR, you should use the `cdr:registration` scope.  The sample request you attached looks like it is using the Register's scopes (`cdr-register:read` and `cdr-register:bank:read`).

Can you please try again using the `cdr:registration` scope?

**Comment by psharma211** [comment]
@CDR-DavidR We are using https://dh-bank.secure.idp.cdrsandbox.gov.au/connect/token API for the CDR Client Credential Token, here there is no scope which is been passed in the header or jwt.

Could you please check and let us know on which call you are tracking this. Attached is the request body and header details for reference, request you to correct us if we are missing anything.
[sb-logfile-20221111-055839.csv](https://github.com/ConsumerDataRight/sandbox/files/10020988/sb-logfile-20221111-055839.csv)

**Comment by CDR-DF** [comment]
Hi @psharma211,

The decoded client assertion provided in the attached log file csv can be seen on: [jwt.io](https://jwt.io/#debugger-io?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiIsImtpZCI6IjE4NzI2MjQ5MzgzMTc3NzU4NjgxNzc2NTY0NjE4ODYxNTc1MzA2In0.eyJhdWQiOiJodHRwczovL3NlY3VyZS5hcGkuY2Ryc2FuZGJveC5nb3YuYXUvaWRwL2Nvbm5lY3QvdG9rZW4iLCJpc3MiOiI3MWJjMDBlOC1jZmVhLTQ3YjQtYWFmMy00YTA3MzRiYjA5NGYiLCJzdWIiOiI3MWJjMDBlOC1jZmVhLTQ3YjQtYWFmMy00YTA3MzRiYjA5NGYiLCJqdGkiOiJlODdmMWVkMi1lYjE4LTRkMGMtYTY0ZC04ZTk0YWFkMjU1ZDciLCJleHAiOjE2NjgxNDk0MTcsImlhdCI6MTY2ODE0NTgxN30.GyLAtXmfPT2szN0eJbKqCDexr0Pv6nSL6IrLZCqLRUpzvqAGJlXXX90OL5GEsUXzS6QHCOdcCGpXnyTWF9LvvCkGqFL6bkbOC_XbMI07kXaNUi6Sr0QTADLGqp7XSbP1maH0EruE6pffcmH00tpYfwpA8-4QDObH0ey3lsV5c3KyvLOtU_IDpzwqWQis0jIfXghbDoYqBZRNo-GhTrZ_fIR9h1SLFijHlqWw5hyOoVoSNCYJX7gcZwiLt2tVbqgbPyg6-vPfv_clWOLHNu3ouhHjeJM-hKVvXqIVWhnypD1s2A0IJchgzzh47kVYrsvNicK4lfb4eLnPp_86201YZg)

The client assertion includes an `aud` claim that is set to `https://secure.api.cdrsandbox.gov.au/idp/connect/token`, i.e. the CDR Sandbox Register's token endpoint.  Therefore it looks as though you are using a client assertion that is intended for the CDR Sandbox Register's token endpoint, rather than the Data Holder's token endpoint (`https://dh-bank.secure.idp.cdrsandbox.gov.au/connect/token`).

Can you please try again and set the `aud` claim of the client assertion to `https://dh-bank.secure.idp.cdrsandbox.gov.au/connect/token`.

**Comment by psharma211** [comment]
@CDR-DavidR we tried again and now error is changed.
Please look into it.

Request: curl --location --request POST '[https://dh-bank.secure.idp.cdrsandbox.gov.au/connect/token'](https://dh-bank.secure.idp.cdrsandbox.gov.au/connect/token%27) \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_id=71bc00e8-cfea-47b4-aaf3-4a0734bb094f' \
--data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' \
--data-urlencode 'client_assertion=eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiIsImtpZCI6IjE4NzI2MjQ5MzgzMTc3NzU4NjgxNzc2NTY0NjE4ODYxNTc1MzA2In0.eyJhdWQiOiJodHRwczovL2RoLWJhbmsuc2VjdXJlLmlkcC5jZHJzYW5kYm94Lmdvdi5hdS9jb25uZWN0L3Rva2VuIiwiaXNzIjoiNzFiYzAwZTgtY2ZlYS00N2I0LWFhZjMtNGEwNzM0YmIwOTRmIiwic3ViIjoiNzFiYzAwZTgtY2ZlYS00N2I0LWFhZjMtNGEwNzM0YmIwOTRmIiwianRpIjoiNjBjYjJlMTktY2E5MC00NTU2LWE3YjMtM2U1NzBlZmYyYTc5IiwiZXhwIjoxNjY4NzUzMjU4LCJpYXQiOjE2Njg3NDk2NTh9.EHM2yoY3hjjjavl7GxtMPag_PrwnLjjuGFrDmr19i5eTG2y15t0g6Ywn4dtFtkNYp0ijKCO043KAXU8cuggbYcIg7O8FY5cEZ92--whFAObOEUQE3ZSLULQXjxB1fvGeA2rWxpxDP1Kn6A46cViJKGAcK8QXRTe_K2zljAyctpK8EU04J9sna2650Pax3ZyYLp-w06Gn-8F0vq90rlT_j4ip9OoJG8aOfqGlpoqtuDUanAqSB3G4jAUx9SgqzvKFjyJn-a4X8GUVDVi-HIKPYyREvlg374vtTwqcK85DXwiP_skIKauj72K94pPeE3hcWzSXA7pZ5xb4kyLDIC8vzQ'


Response: 
{
    "error": "invalid_request",
    "error_description": "Token request invalid redirect uri"
}
Response Code: 400 Bad Request

**Comment by CDR-DF** [comment]
Hi @psharma211,

Can you also add `--data-urlencode 'scope=cdr:registration'` to your token request form parameters?

**Comment by psharma211** [comment]
@CDR-DF thank you. Above parameters resolved the issue at our end. We can close this ticket.
