### ISSUE TITLE
JARM Support in CDR sandbox

### ISSUE THREAD

**Issue by psharma211** [ConsumerDataRight/sandbox#17]
Hi @CDR-DavidR can you please let us know when we can test JARM feature using CDR sandbox. We have completed the implementation and want to test this feature at earliest. Please help to share the timelines when we can plan to test it.

**Comment by CDR-AndrewG** [comment]
Hi @psharma211,

We are looking into updates for FAPI 1.0 Phase 3 now. Aiming for a release in the early new year.

**Comment by psharma211** [comment]
@CDR-AndrewG can we get the dates for this.

**Comment by psharma211** [comment]
@CDR-AndrewG @CDR-DavidR  can we get dates when we can test JARM using Sandbox?

**Comment by CDR-AndrewG** [comment]
Hi @psharma211,

We are currently aiming for an end of February release which will include Data Holders and Software Product that support JARM.

**Comment by psharma211** [comment]
@CDR-AndrewG @CDR-DavidR please confirm if deployment is completed and we can test JARM feature using CDR sandbox.

**Comment by CDR-AndrewG** [comment]
Hi @psharma211, Yes, the JARM feature is now available in the CDR Sandbox.

**Comment by CDR-DF** [comment]
Hi @psharma211,

It looks like the request object that you are sending in the PAR request is missing the "response_mode" parameter in the JWT.  Set the "response_mode" to "jwt" to enable JARM.

As per **FAPI 1.0 Advanced**: 
In addition, if the `response_type` value `code` is used in conjunction with the `response_mode` value `jwt`, the authorization server shall create JWT-secured authorization responses as specified in [JARM]

**Comment by psharma211** [comment]
Thank you @CDR-DF. I will check and update you after testing.

**Comment by psharma211** [comment]
Thank you @CDR-DF for your help.

JARM support testing was completed successfully. We have some open queries please help with that.

1. **CDR Sandbox** is working without passing authorization_alg and enc; so can we assume that it's not mandatory for live providers as well?

2. **PUT DCR for JARM support:** is PUT DCR mandatory to support JARM changes for live providers as well? Currently, we do not have platform support to do PUT DCR call so need confirmation on this.

**Comment by CDR-DF** [comment]
That's good news @psharma211!

To answer your other questions:

1. Data Holders will advertise their support for JARM encryption in their OIDD using the `authorization_encryption_alg_values_supported` and `authorization_encryption_enc_values_supported` fields. JARM encryption is optional and is not recommended to be implemented by data holders at this time:  

> JWT Secured Authorization Response Mode for OAuth 2.0 (JARM) Data Holders MAY support Authorisation Response encryption.
> However, at present, there is no confidential information in the authorization response, hence encryption of the authorization response is not required for the purposes of security or confidentiality. In addition, whilst response encryption MAY be used, to achieve greater interoperability, it is not recommended to use encryption in this case at this time.

Although JARM encryption is not recommended, it is optional, so a data holder **MAY** support Authorisation Response encryption.  Something to be aware of in case you encounter this in the CDR ecosystem.

2. If your software product is currently registered with Data Holders, then you will need to perform a DCR PUT to update your registration information for FAPI 1.0 Phase 3 obligations, including support for authorization code flow (`"response_types": ["code", "code id_token"]`) and JARM signing algorithm (`"authorization_signed_response_alg"`: `"PS256"` or `"ES256"`).

**Comment by CDR-AndrewG** [comment]
Hi @psharma211,

If you would like to test against a Data Holder in the Sandbox that requires JARM encryption, you can use the `Sandbox Energy Data Holder` - https://dh-energy.idp.cdrsandbox.gov.au/.well-known/openid-configuration
