### ISSUE TITLE
Multiple Redirect URI Support

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataRight/sandbox#2]
**Describe the bug**
The Sandbox does not appear to support multiple redirect uris for Software Products:

**To Reproduce**
1. Create a software product

**Expected behaviour**
Multiple Redirect URIs must be supported.

**Screenshots**
![image](https://user-images.githubusercontent.com/4291448/183269547-0eb7df33-c236-4e1f-a6d5-9a9a0667302b.png)

**Additional context**
![image](https://user-images.githubusercontent.com/4291448/183269571-268613ba-584e-4577-a47f-43bfcd31d68b.png)

**Comment by CDR-AndrewG** [comment]
Hi @perlboy,

Thank you for getting in touch with us to raise this issue. The information provided and notification of the issue will greatly help to us make the sandbox more closely aligned with the CDR ecosystem.

We have logged the issue and will include a fix in a future release.

**Comment by CDR-AndrewG** [comment]
Hi @perlboy,

This issue has been resolved in our latest Sandbox release.
