### ISSUE TITLE
CDR Sandbox Account Details API returns 404

### ISSUE THREAD

**Issue by psharma211** [ConsumerDataRight/sandbox#22]
**Describe the bug**
CDR Sandbox Account Details API returns 404; even "https://dr.cdrsandbox.gov.au/data-sharing-banking" says it is supported

**Expected behaviour** API call must be successful

Error : description *********
We are trying to access the CDR Sandbox Account Details API, however we are seeing 404 not found exception. Current version we are using is x-v as 2, could you please help us understand if this is supported for Sandbox Portal.
Url: https://dh-bank.resource.api.cdrsandbox.gov.au/cds-au/v1/banking/accounts/kJKLAup0KvF4EHSXu4h%2F818qjHchnflHKEdan6lao+xrgWMvHsUz1u+nrD+61qY6
x-fapi-auth-date:Thu, 05 Jan 2023 10:46:48 GMT
Response code : 404
Response msg : Not Found

Let us know if you need any additional details. 

Thanks !

**Comment by CDR-DF** [comment]
Hi @psharma211,

I've checked the Sandbox Banking Data Holder implementation and the Get Account Details API is currently not supported.

The Sandbox Banking Data Holder currently only supports:

- Get Customer
- Get Accounts
- Get Transactions

**Comment by psharma211** [comment]
@CDR-DF thank you for the update. we will wait for your update when we start supporting it.
