### ISSUE TITLE
CDR Sandbox and support for revocation arrangement notification

### ISSUE THREAD

**Issue by awwkoala** [ConsumerDataRight/sandbox#23]
**Describe the bug**

Hi! 
While testing our authorization product with your CDR Sandbox, I noticed that when doing an arrangement revocation, notifying CDR Sandbox results in response with http code greater than 400 and response body: `7b226572726f72223a22696e76616c69645f746f6b656e227d` . 
I was wondering if you even support revocation arrangement notification?

**To Reproduce**
1. Revoke arrangement with external service which sends a revocation arrangement notification.
2. Check response from CDR Sandbox.

**Comment by CDR-AndrewG** [comment]
Hi @awwkoala,

To help us trouble shoot, can you please try again and supply the log file from the Sandbox that contains the requests and responses?

How to download the logs is covered here - https://consumerdataright.atlassian.net/wiki/spaces/PT/pages/9240629/How+to+download+My+Logs

**Comment by CDR-AndrewG** [comment]
Hi @awwkoala,

Are you still experiencing this issue? If so, please provide some more information. Either the downloaded logs or more detail in the steps to reproduce will help us to troubleshoot the issue.

**Comment by CDR-AndrewG** [comment]
Hi @awwkoala,

Please reach out if you are having any other issues.
