### ISSUE TITLE
DCR fiaied and can not capture logs 

### ISSUE THREAD

**Issue by Buddy119** [ConsumerDataRight/sandbox#24]
**Describe the bug**
After created the daba holder brand, The DCR always display failed. We do not find any logs in My Logs and also do not find any request from sanbox IP: 20.53.130.184

**Expected behaviour**
DCR can be success

**Screenshots**
highlight in blue
![image](https://user-images.githubusercontent.com/13232171/218276597-9e066a7b-70d4-4522-b830-b37cdc7ef683.png)

**Comment by CDR-AndrewG** [comment]
Hi @Buddy119,

Thank you for reaching out. The Dynamic Client Registration function running in the Sandbox needs to use the InfoSecBaseUri of your Data Holder to find the token and registration endpoints.

It looks like the discovery document cannot be accessed and therefore the token and registration endpoints cannot be found - https://public-qa.ob.hsbc.com.au/.well-known/openid-configuration

For example, this is the discovery document for the Sandbox Banking Data Holder - https://dh-bank.idp.cdrsandbox.gov.au/.well-known/openid-configuration

**Comment by Buddy119** [comment]
Hi @CDR-AndrewG 

After enable the IP restricition, we can received the request from sandbox. But the DCR still failed. We checked the log and found that the reuqest from sandbox violate the register standard. Please check below

1, According to CDR standard, the redirect_uris in JWT should be an array. But what we received is not an array. Can you help check? 
![image](https://user-images.githubusercontent.com/13232171/219844048-83ecfd30-7937-4d57-bb08-b5916e8b5360.png)

2, We checked the IP address from sandbox. But found that the IP address of sandbox is not 20.53.130.184  Can you help check?
![image](https://user-images.githubusercontent.com/13232171/219844118-56a5afc2-933f-4539-a2af-76cb1abb4592.png)

**Comment by Buddy119** [comment]
@CDR-AndrewG  the standard link we refer: https://consumerdatastandardsaustralia.github.io/register/#dynamic-client-registration

**Comment by CDR-AndrewG** [comment]
Hi @Buddy119,

We have logged the issue and will include a fix in a future release.

Regarding the IP you are expecting, `20.53.130.184` is the IP address of the Sandbox Data Recipient, `dr.cdrsandbox.gov.au`. Any requests from the Sandbox Data Recipient, such as a registration request (DCR) to a Data Holder, should be received from `20.53.130.184`. Can you give some more details on the other IP address you mentioned?

**Comment by CDR-AndrewG** [comment]
Hi @Buddy119,

This issue has been resolved in our latest release of the Sandbox. The redirect_uris will now always be presented in a string array.
