### ISSUE TITLE
Cannot load the sandbox portal

### ISSUE THREAD

**Issue by Aiden-Ziegelaar** [ConsumerDataRight/sandbox#25]
**Describe the bug**
I cannot load the sandbox portal, legal entities call is failing:
```
https://manage.api.cdrsandbox.gov.au/management/legal-entities
500 Internal server Error
```
**To Reproduce**
Steps to reproduce the behaviour:
1. Login to sandbox portal
2. See error

**Expected behaviour**
The sandbox portal should load correctly

**Screenshots**
![Screen Shot 2023-02-16 at 10 04 15 am](https://user-images.githubusercontent.com/19164243/219248861-9819c4a5-0f5c-4f7c-873b-2c282bdd3345.png)

**Additional Context**
None

**Comment by CDR-AndrewG** [comment]
Hi @Aiden-Ziegelaar,

Apologies for the inconvenience. This issue has been resolved. Let us know if you experience any further issues.

**Comment by Aiden-Ziegelaar** [comment]
Thanks for the speedy turnaround!
