### ISSUE TITLE
CDR Sandbox does not support different ACR values

### ISSUE THREAD

**Issue by Aiden-Ziegelaar** [ConsumerDataRight/sandbox#26]
**Describe the bug**
According to the standards:
> READ operations SHALL only be allowed where at least an LoA of 2 has been achieved during the establishment of consent.
> WRITE operations SHALL only be allowed where:
> * At least an LoA of 3 has been achieved during the establishment of consent, or
> * At least an LoA of 2 has been achieved during the establishment of consent and a subsequent challenge/response has resulted in an LoA of 3 being achieved within the lifespan of the current Access Token.

Given all energy endpoints at the moment are `read`, we are only supporting an LoA of 2. However, even though we are not advertising an LoA of 3 in our discovery document, the sandbox still attempts to make a request with an LoA of 3. 

**To Reproduce**
1. Login to CDR Sandbox Data Recipient
2. Attempt to create a par request, using the details:
    DH Brand: EnergyAustralia-TEST (bac1eb3b-727b-48bd-8fd5-94c87ca8a686) - (858007cbf3474c8b92bf105dc126b7d3)
    Create new arrangement
    Duration: 2140000000
    Scopes: openid profile common:customer.basic:read common:customer.detail:read bank:accounts.basic:read bank:accounts.detail:read bank:transactions:read bank:regular_payments:read bank:payees:read energy:accounts.basic:read energy:accounts.detail:read energy:accounts.concessions:read energy:accounts.paymentschedule:read energy:billing:read energy:electricity.servicepoints.basic:read energy:electricity.servicepoints.detail:read energy:electricity.der:read energy:electricity.usage:read cdr:registration offline_access
    Use PKCE: true 
    Response Type: code id_token
    Response Mode: fragment
  `{"error":"invalid_request_object","error_description":"The request parameter contains an invalid Request Object","error_hint":"requested claim acr should be one of [urn:cds.au:cdr:2]","status_code":400}`

**Expected behaviour**
The sandbox should make a request with an LoA of 2 when an LoA of 3 is not advertised as supported.

**Comment by CDR-AndrewG** [comment]
Hi @Aiden-Ziegelaar,

Thank you for getting in contact and raising this issue. We are currently investigating the issue.

**Comment by CDR-AndrewG** [comment]
Hi @Aiden-Ziegelaar,

This issue has been resolved in our latest release of the Sandbox.
