### ISSUE TITLE
EA : Unable to access https://dr.cdrsandbox.gov.au/dcr - getting 502 Bad gateway

### ISSUE THREAD

**Issue by VinayakEA** [ConsumerDataRight/sandbox#27]
**Describe the bug**
When trying to access https://dr.cdrsandbox.gov.au/dcr - it is throwing 502 bad gateway

**To Reproduce**
1. Access https://dr.cdrsandbox.gov.au/dcr
2. See error

**Expected behaviour**
When access https://dr.cdrsandbox.gov.au/dcr - it should be able to proceed with ADR operations

**Screenshots**
Attached
<img width="1710" alt="image" src="https://user-images.githubusercontent.com/113506088/226217474-6ec9fcd8-781c-45e1-8fde-e5a94a7b13ad.png">

**Comment by VinayakEA** [comment]
Hi Team, we are not able to access https://github.com/ConsumerDataRight/sandbox/issues/27 and throwing 502 Bad Gateway - it is blocking EA testing hence request you to please look into it on priority

**Comment by CDR-AndrewG** [comment]
Hi @VinayakEA,

The issue has been resolved now. Apologies for the inconvenience.

**Comment by VinayakEA** [comment]
Thanks @CDR-AndrewG
