### ISSUE TITLE
"sharing_expires_at" is not coming as part of /token response for CDR sandbox

### ISSUE THREAD

**Issue by psharma211** [ConsumerDataRight/sandbox#28]
**Describe the bug**
"sharing_expires_at" is not coming as part of /token response for CDR sandbox

 
**To Reproduce**
**Steps to reproduce the behavior:**
1. /par call to be done with the registered client id
2. Authorize the flow with credentials
3. /token API call, check the response for the successful call

**Expected behavior**
sharing_expires_at to be part of the response for /token call

 

**Screenshots**
Attaching Response for reference-
{
    "body": {
        "access_token": "eyJhbGciOiJQUzI1NiIsImtpZCI6IjdDNTcxNjU1M0U5QjEzMkVGMzI1QzQ5Q0EyMDc5NzM3MTk2QzAzREIiLCJ4NXQiOiJmRmNXVlQ2YkV5N3pKY1Njb2dlWE54bHNBOXMiLCJ0eXAiOiJhdCtqd3QifQ.eyJpc3MiOiJodHRwczovL2RoLWJhbmsuaWRwLmNkcnNhbmRib3guZ292LmF1IiwiY2xpZW50X2lkIjoiNzFiYzAwZTgtY2ZlYS00N2I0LWFhZjMtNGEwNzM0YmIwOTRmIiwic3ViIjoiSXl3V3VBMGtlT1QzcTRrSmdXeWUvZz09Iiwic29mdHdhcmVfaWQiOiJlY2Q5MDMwZi03ZGMxLTQ0YTEtODc0Mi0wOWIyOTZhN2I5NjUiLCJqdGkiOiI1OTJhNDk5Yi03ZGQ3LTRjY2UtYWExNS1kNmU2MGI1MmYzYTgiLCJhdXRoX3RpbWUiOjE2ODY1NjA3MDIsImNvZGUiOiJmNzljOGJkYy1hNGJkLTQ3MmYtODM0Ny03ODM1N2U3YTMxYTciLCJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIiwiYmFuazphY2NvdW50cy5iYXNpYzpyZWFkIiwiYmFuazp0cmFuc2FjdGlvbnM6cmVhZCIsImNvbW1vbjpjdXN0b21lci5iYXNpYzpyZWFkIl0sImNkcl9hcnJhbmdlbWVudF9pZCI6Ijk0ZWVhYThlLTFhOGUtNDhjZS1hMjQ5LTQ0Nzk2NmJkM2VkMyIsImNkcl9hcnJhbmdlbWVudF92ZXJzaW9uIjoxLCJzZWN0b3JfaWRlbnRpZmllcl91cmkiOiJkaXQxLW9jY20uY29ycC55b2RsZWUuY29tIiwiYWNjb3VudF9pZCI6WyJVVCUyRmZVSHF0QTlnakFLdjVuZVpUYmc9PSIsImdNcnY1V3ZNQWNURXNLN0I0dDlBRGc9PSJdLCJjbmYiOnsieDV0I1MyNTYiOiIxMGNlMTZlZjU4NmU5ZWRmMGEzNmNhODkxYTVmMGYyZjRjMDkxZDhkIn0sIm5iZiI6MTY4NjU2MDcwMiwiZXhwIjoxNjg2NTYxMDAyLCJpYXQiOjE2ODY1NjA3MDIsImF1ZCI6ImNkcy1hdSJ9.V0h4P03KMHZhkqIuRoB3haTzRo5zDVqbJpXrORt7mqM0c5Nc8QuOPq3anXN9xeCGRLGercxG5ppvQJ9rNZ6ybaJ8Zi37NMtWaX4mM1lnM4-BZ6z-kxFz5pDu4hOUT6gWyQz1CAYRbk8EZr5kn32RlmFcQjFOp0Nmst8XfWhHNb3kfug8lgatMFx5vspFGz6bEFBLkOESFjtDEt8JgTIIDVhZ81R93Q0n-XQcZtxWRVQMgkTaeFZV5VDgWw4PO1hBObqjTTcx9MxIsCDMnMk_8ujqqP5oaVJrh66cjb1IcHe3VdakdViTX0WY0Mv3WgJcwZQl8Hh2kXvgW2QzNIejNG-HxiVe8xBtHfMf6rZMKrYBJ3-rOiAMF3r_zqARGyH4Ect6rzo4lfFYuP5BJxN1SupH8vGH3txGVMG74HG09Q148FviNR-maNLQSj-9YqZAC7tSCRVx6yF6ZjVA7m_zar8R2eLiKqzbW2vfp_PILOT9ScnsgnVTbukFmBHTOr_q",
        "refresh_token": "608eb1ef-854a-442c-bcb5-e876252f57a2",
        "cdr_arrangement_id": "94eeaa8e-1a8e-48ce-a249-447966bd3ed3",
        "eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZHQ00iLCJraWQiOiIzMjMxMDcxNDc2MjM0MDg1NTM0NTAwMDE5MDc4NTc4NTY1ODQ5In0.NZvG-z3xRQJeL_d22YgoDI4Bf4J6NU7x3cEyrcF9tXzRgw24ViOG8u6CXnudeKvMM-23cDOwfr6VMFMJCYG5kXgtreYNSTFf4ZScRsn1U_LzSZlT-o0pG3IYr2vKFJOSNe43VtO8saNcwu2JLuWzv_-7gG8LVHCojTVIGvyRHppouxdDYSNYiJ4fJH-QjU98IC4cKfF5Sjm3wLCFz2kV1pqw4GUL9H1k2AS7VqQXIxUb0WYVqmi0_I0PCQMZfRXc9iMhamrqemHI1Fuhs2miHJWgfLKr9zpZqdUQhu4CRLhoYZSI6Pr9vFDE2Sk0h9LM93HBE_6shTEOXEs78uT0SQ.jLMVBpu4w9W-uA2X.MrHsyt4bsopwH22VkMJ75ARX7aus6ws6BYj91dufJ7HlzkH0JvBSAB41u4-U_2MYtJm4HXt_TlW82mwrJpuxCZCt-hQZdv4kjPIH_GKbhRDR0a-RHVGAiizN1Kw0LL91pc4ol1NR-OHhRA17nxesj73JHkTXMDZr9zy11lt-Vk3fZqSejYXLltAx7Ksyt_Gsf0jjQowDkujXBevXXI84z6u0JRMjP4CovivpsKpCFNLV7hPnX0v6UmU04lhAAm7EDuUlbBivCU_xqYevq34LROWT7m-0zJxx3cMi9A_DxnOf8ZuIWOfCE5oGCPLFWwINVyFj0h6ac5_BX8VYqLODhcipEw0aOxHKgA3avdQOuSxI7Y2QCcRz0IyPSQbfr31Ht5DH-xDMuoMnaqmiTSM3gOZhyrJ0TCGM3WLdrd2V-JuJlhg3bp9fqx4_oOdtvErwX8D7SYK-LkYJlBdUTuZffn3TnPTXw1YopsxH2oU2jfgXNiO2CiEtnIR07UXJs27kd-2DhVEiG97awootGf5DzHm_FHFxGgi8tFfX2Tn4m71RPibRfxlBA1vlM5QufYrgpLfA65ZrofGmtAKzYsiRMhQBP9lmm7--JaRGTyDBQActPCb0zo4bPTMWJIu0imDw8kXfc30y5DVhfKzPBNcUfo2C1JfuQStb4gOuW1yv2PJ9gG93V_cLfSRs8q_l2-BFcHfH-jARq_LCtYv4DfWafqbqwUSzZ7zAJdLGpZkas5SPxY2dGNITEOjJT7dv9WIvZK6EhleJFN9k7xz_OJ9dniePDtRdd5IQ9x2QUtTJgzB5tLIKspNMuUGFbU0GmAES09_XmxMmt3rRd2xZXT31SQNPl_uWQnlKpzA_AKdgB0YmUU7XvfZWUDh2DN-RoYt8Ykr2uwPn2tgeG1ee-mKuKgwZK2_50XiADcLXGEbc2utB_A9_yVDKuAO75RCOrkb0qKnQ3p3A8oE_1a0PTMLqp9Ru7yO_MDPpDYGCZJubsfmhfSwWPzVOBLzP3sK7Q6rq-vKLYTav8P-5493C-8kn7hhWSjcUnku0dFzx3bboSN06gHN-tNtatgwOvJmsM8Crji6BgYEjL_9B_ghjtD93rVVEbCcY9Z-J4kbxEF6NgX-qk65PeRJttC3zgEkMPbZEe9SS2EiBojJ08SANP5k3w82jMxHKRy12KCUdlrsDF2ZcuR79UJkC5EfWj2wQGlNY6oKjiNW9glBkxV_3MhXLFdvcDU0h1t2qILmIkaklw-ll-irAq6Uowaj5y1psFPAIVNhHm068xsIBZrg7hDdVVAYCVs0qYgVmB-SPQ1TER7tp3MXAccbubHnR9SkLtz8MjIawUPaq9Nn4HFczSLNPsXTdHQqhC94UAYh5Pdi3WigHLQ_nxggcBQacTh7prX2AimOwyQa7VnH0HrIg91OOAB7SaQ_eIA-fLV-TeCKe9Kd6-7sqop0iOI3MsJO41hUzPZUv3XCP4N4_lLJ_ENAwR4Sycup2n3c.dMkpX3CDHcJfMWBGLN17aw": "eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZHQ00iLCJraWQiOiIzMjMxMDcxNDc2MjM0MDg1NTM0NTAwMDE5MDc4NTc4NTY1ODQ5In0.rlTykKvg3GeTMJUDxjSJXzDKGwRwirSoVi3zLbvPtV521i97-Iqn42msVI6yp9FSUTwrKzYKa8yMK22F2gio7y5YQ5yVyilH8n6-G00OMcYprfk1ZBcjywzY2KO389vMrtRCFunPrtMFdKLDr2kNOtg9GZBMEK0bh8FsSfaB9X_EOm-4kiGG2FvNOfCKlErHjZNJUjUNWciz-KY50vYpONs6svw8WwhtqdwyLFtpErYGg5_K8bEIRAPDHx3XQRjxMn1zbjIFj36e7tMLX_TIJcbp6QuSMg8rry87am8ml2jd50uk-2AuL8dfI6PWyPUy090rPmBPKCvCc1Od9e5SvQ.09nEhLDoHgL4UAX9.B24VZe6jhQk61R965xRS-BD6Fms07YIlaUqlZNQ3K9IW1oN3mEQFOYMOK9QpotoBwvDMAQQGq-Gdjbp8rLGwaYTR3urabs7UQjugy1gf2vP5R5BJrcNu-BUdgWM-jYywLgEQYC3WyibHwf76-W1L0_99nXxWayBjJJG14wDqVuV8KetlYfa33ceuWEioo4sFn8gZvjRwmzb6fX8oQByaj87mi13tAnKhMPmrM_eI8g0AG8nD6CnNVYyu2j0zPHAqhQfXbyGblWXcfyKo5jaPa8LTamiq_KWxyM7kT48O9fI6taJzqKkKszDuOeUT5m9kjNIdq4dW49kNsMkzTmAnNugDYsjM8cWOvATBweXQNyci0OgRL8FyrRhW1nr_efaiwyk2nr4FR8zAy4VQb6gnJacXUDNrPBWQNhVPp8LEvLuFJQMVWPozNwkIUIWejhS-OzGA0fggwYxVgsuw-kXdhWSDbQ-n_bHXgJdTP8nb9FoMDg1nkdprprlSsxxHEH0XXAEIkNfkUD_ZVmGuYpc-6MRnf9K5lrJwW5NSw6yU6VZbIcnY47L1PvqbLrCAWgX8zgwp-i49Dv5hD02gUM6z5qpq5Z-MQqV_ZLqU9kyr4xWGMbULwC7t0VbEqJwpRSahO_mSRGV4k0xCpUGlZ9MVM76Okb5KXrZkluyfxZO8ZaXqyjiB7KNLV_afUnMM4jIUJRH52qc0bm4y2FaFqXgH82PAqnPzH1jQ1KzFumKw2dzhx5Z8zTbhJir--9I_LnEgWBsCBrJL77D0PbUELHG1zji1lFGZMLj0ICDxNL2wn7niEgU55ceSYY6-xIxl5CZvhcFmMpzQgwYMkab65gC58U1HuL5WZxWxhxhcxIFUGR0q_l0aZBDMsA36BWAu2dM0RiLXBaA2QqGzmjl0xR7sXvwXHXNW1ZM3gZihNneGSnRyGuLUohFRTD9e4UpJsKmvuaBXrdH47n-QwNSoT7L3zXjpVHS3eG2dRGq6Fd-ucTvzWvg8J6oh9jTqTnjWZAU5f8hdQ1DCw1vfbrlhq3TreKsUhXPyqy9G1dOnUbBwkVi13UhZ6wrKEE31slVNb_pDqyXb7kXImmeH6N73h0AEsPWBDnAdCUUFjUk6Wpv7z386nzPSkB4iIblpbwc-XBwx-LbaCJ72lMUzARj_kq_gDbud1nSH15yhSxUV8SkjYh0R29TIsliGIRhXhZglmWScv90mt0i_3TseGzMbuXP6axqRRHTDWj1VTawphWUedH9xjMJoBvsU-t96H426f040Z4RpQorUnTssPiOGzWBd6ue5PBD5PaZCVj8vIbPQYp3HR2muh3qyU9Yf5zWsn5XPG9lLuL_KEkWF5nBV_bmklG-ot_bbtfYoWVIhXaLHcFJ8J9o8zxrYrJBpv2kFSwNMr98nY1OjKcRZVipnI4wW4GSIEzKYCm2UArwwug7hZ2NHnYzh1MzxuA_dL_YmzvOX6T3dL7C6NH_DqG1xE3HWo0r3MqHQ8NS52UXTIUVyPU9KIUZZPZIdGL9Soa8K_seWjn5eus-929gMl_xumjBbAj1pe-iinlbjsRXzrkx1GwHN4-voJFIehTiaxCbW7-dzXK4RC5JWFnEMxQ.oQg0PKiHgMBmJv72C1_oWQ",
        "scope": "openid profile bank:accounts.basic:read bank:transactions:read common:customer.basic:read",
        "id_token": "eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZHQ00iLCJraWQiOiIzMjMxMDcxNDc2MjM0MDg1NTM0NTAwMDE5MDc4NTc4NTY1ODQ5In0.rlTykKvg3GeTMJUDxjSJXzDKGwRwirSoVi3zLbvPtV521i97-Iqn42msVI6yp9FSUTwrKzYKa8yMK22F2gio7y5YQ5yVyilH8n6-G00OMcYprfk1ZBcjywzY2KO389vMrtRCFunPrtMFdKLDr2kNOtg9GZBMEK0bh8FsSfaB9X_EOm-4kiGG2FvNOfCKlErHjZNJUjUNWciz-KY50vYpONs6svw8WwhtqdwyLFtpErYGg5_K8bEIRAPDHx3XQRjxMn1zbjIFj36e7tMLX_TIJcbp6QuSMg8rry87am8ml2jd50uk-2AuL8dfI6PWyPUy090rPmBPKCvCc1Od9e5SvQ.09nEhLDoHgL4UAX9.B24VZe6jhQk61R965xRS-BD6Fms07YIlaUqlZNQ3K9IW1oN3mEQFOYMOK9QpotoBwvDMAQQGq-Gdjbp8rLGwaYTR3urabs7UQjugy1gf2vP5R5BJrcNu-BUdgWM-jYywLgEQYC3WyibHwf76-W1L0_99nXxWayBjJJG14wDqVuV8KetlYfa33ceuWEioo4sFn8gZvjRwmzb6fX8oQByaj87mi13tAnKhMPmrM_eI8g0AG8nD6CnNVYyu2j0zPHAqhQfXbyGblWXcfyKo5jaPa8LTamiq_KWxyM7kT48O9fI6taJzqKkKszDuOeUT5m9kjNIdq4dW49kNsMkzTmAnNugDYsjM8cWOvATBweXQNyci0OgRL8FyrRhW1nr_efaiwyk2nr4FR8zAy4VQb6gnJacXUDNrPBWQNhVPp8LEvLuFJQMVWPozNwkIUIWejhS-OzGA0fggwYxVgsuw-kXdhWSDbQ-n_bHXgJdTP8nb9FoMDg1nkdprprlSsxxHEH0XXAEIkNfkUD_ZVmGuYpc-6MRnf9K5lrJwW5NSw6yU6VZbIcnY47L1PvqbLrCAWgX8zgwp-i49Dv5hD02gUM6z5qpq5Z-MQqV_ZLqU9kyr4xWGMbULwC7t0VbEqJwpRSahO_mSRGV4k0xCpUGlZ9MVM76Okb5KXrZkluyfxZO8ZaXqyjiB7KNLV_afUnMM4jIUJRH52qc0bm4y2FaFqXgH82PAqnPzH1jQ1KzFumKw2dzhx5Z8zTbhJir--9I_LnEgWBsCBrJL77D0PbUELHG1zji1lFGZMLj0ICDxNL2wn7niEgU55ceSYY6-xIxl5CZvhcFmMpzQgwYMkab65gC58U1HuL5WZxWxhxhcxIFUGR0q_l0aZBDMsA36BWAu2dM0RiLXBaA2QqGzmjl0xR7sXvwXHXNW1ZM3gZihNneGSnRyGuLUohFRTD9e4UpJsKmvuaBXrdH47n-QwNSoT7L3zXjpVHS3eG2dRGq6Fd-ucTvzWvg8J6oh9jTqTnjWZAU5f8hdQ1DCw1vfbrlhq3TreKsUhXPyqy9G1dOnUbBwkVi13UhZ6wrKEE31slVNb_pDqyXb7kXImmeH6N73h0AEsPWBDnAdCUUFjUk6Wpv7z386nzPSkB4iIblpbwc-XBwx-LbaCJ72lMUzARj_kq_gDbud1nSH15yhSxUV8SkjYh0R29TIsliGIRhXhZglmWScv90mt0i_3TseGzMbuXP6axqRRHTDWj1VTawphWUedH9xjMJoBvsU-t96H426f040Z4RpQorUnTssPiOGzWBd6ue5PBD5PaZCVj8vIbPQYp3HR2muh3qyU9Yf5zWsn5XPG9lLuL_KEkWF5nBV_bmklG-ot_bbtfYoWVIhXaLHcFJ8J9o8zxrYrJBpv2kFSwNMr98nY1OjKcRZVipnI4wW4GSIEzKYCm2UArwwug7hZ2NHnYzh1MzxuA_dL_YmzvOX6T3dL7C6NH_DqG1xE3HWo0r3MqHQ8NS52UXTIUVyPU9KIUZZPZIdGL9Soa8K_seWjn5eus-929gMl_xumjBbAj1pe-iinlbjsRXzrkx1GwHN4-voJFIehTiaxCbW7-dzXK4RC5JWFnEMxQ.oQg0PKiHgMBmJv72C1_oWQ",
        "token_type": "Bearer",
        "expires_in": 300
    },
    "responseCode": "200"
}

**Comment by psharma211** [comment]
@CDR-DavidR could you please share an update?

**Comment by CDR-AndrewG** [comment]
Hi @psharma211 ,

Thank you for raising this issue. 

Can you please confirm what value is being passed through in the `sharing_duration` claim in the authorisation request?

**Comment by psharma211** [comment]
Hi @CDR-DavidR [@CDR-AndrewG ]
"sharing_duration": 31536000

this is the value we are passing in /par and then /token we are expecting to get sharing_expires_at.

Thanks!

**Comment by psharma211** [comment]
@CDR-DavidR @CDR-AndrewG  could you please review and update on this?

Currently, there is conflicting information in the standards about the ID token claims 'sharing_expires_at' and 'refresh_token_expires_at'. The ‘Token Expiry’ section states these claims may be retired from 16th September, however, the ‘Scopes and Claims’ section lists that these claims must be supported

Please let us know if the provider does not return sharing_expires_at how we will get the consent expiry date from the provider. do we have other fields to be used or what is the logic.

**Comment by CDR-AndrewG** [comment]
Hi @psharma211,

Thank you for providing the `sharing_duration`. We have logged the issue and will include a fix in a future release.

**Comment by CDR-AndrewG** [comment]
@psharma211 regarding your query:

_Currently, there is conflicting information in the standards about the ID token claims 'sharing_expires_at' and 'refresh_token_expires_at'. The ‘Token Expiry’ section states these claims may be retired from 16th September, however, the ‘Scopes and Claims’ section lists that these claims must be supported_

_Please let us know if the provider does not return sharing_expires_at how we will get the consent expiry date from the provider. do we have other fields to be used or what is the logic._

As part of the CDR transition to FAPI Advanced Profile 1.0, `sharing_expires_at` and `refresh_token_expires_at` claims were no longer mandatory as of 16 September 2022.

I recommend asking a question on the CDR support site for a definitive answer - https://cdr-support.zendesk.com/hc/en-us

The below is an example of how the `Sandbox Data Holder - Banking` and `Sandbox Data Holder - Energy` Data Holder Brands in the Sandbox behave. The below logic is in line with the Consumer Data Standards but there is optional behaviour that Data Holder's may or may not support.

When the Sandbox Data Holder's underlying [authorisaton-server](https://github.com/ConsumerDataRight/authorisation-server) provides an access and refresh token from a PAR request, the `sharing_duration` is used to set the refresh token's expiry date.

The [connect/introspect](https://github.com/ConsumerDataRight/authorisation-server/blob/main/Source/CdrAuthServer/Controllers/IntrospectionController.cs) endpoint can then be used to get the refresh token's expiry date.

I hope the above helps. As the `sharing_expires_at` is no longer mandatory, I will close this issue.

**Comment by psharma211** [comment]
Thank you, @CDR-AndrewG 

we have raised a request in the portal with some more clarifications.
https://cdr-support.zendesk.com/hc/en-us/requests/2013
