### ISSUE TITLE
Wrong data on Get Data Recipients according to CDS Spec

### ISSUE THREAD

**Issue by ThalysGomes** [ConsumerDataRight/sandbox#29]
**Describe the bug**
We are trying to consume Get Data Recipient API from sandbox and we are getting invalid data according to CDS spec: https://consumerdatastandardsaustralia.github.io/standards/#get-data-recipients

**To Reproduce**
```bash
curl --location 'https://api.cdrsandbox.gov.au/cdr-register/v1/banking/data-recipients' \
--header 'x-v: 3' | jq
```
The required field: `accreditationNumber` is missing, which even populating all the fields in UI we couldn't get this value.

**Expected behaviour**
It should enable to populate all mandatory fields from CDS spec for Get Data Recipient API

We only notice one single dataRecipient, which has this accreditationNumber, couldn't find out how that was populated.

**Comment by CDR-AndrewG** [comment]
Hi @ThalysGomes,

Thank you for reaching out. We have logged the issue and will include a fix in a future release.

I can confirm that `https://api.cdrsandbox.gov.au/cdr-register/v1/banking/data-recipients` will return the `AccreditationNumber` if the `AccreditationNumber` is populated in the database. It is currently only populated for the Data Recipient record matching our own Sandbox Data Recipient.

```
"legalEntityId": "18b75a76-5821-4c9e-b465-4709291cf0f4",
"legalEntityName": "Sandbox Data Recipient",
"accreditationNumber": "ADRBNK000099",
"accreditationLevel": "UNRESTRICTED",
"logoUri": "https://cdrsandbox.gov.au/logo192.png"
```

We will look into adding a backend generated unique `AccreditationNumber` for the other Data Recipients in the Sandbox Register.

**Comment by CDR-AndrewG** [comment]
Hi @ThalysGomes,

This issue has been resolved in our latest Sandbox release.
