### ISSUE TITLE
Sector Identifier URI not supported

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataRight/sandbox#3]
**Describe the bug**
Sector Identifier URI is not supported.

**To Reproduce**
1. Create a software product

**Expected behaviour**
Sector Identifier URI is a supported behaviour in production and is the _only_ way to support multiple redirect uris with multiple hostnames.

**Screenshots**
![image](https://user-images.githubusercontent.com/4291448/183269600-4b72bb1c-3f63-4c79-9e0f-a7a1389d5d0b.png)

**Additional context**
Add any other context about the problem here

**Comment by CDR-AndrewG** [comment]
Hi @perlboy,

Thank you for getting in touch with us to raise this issue. The information provided and notification of the issue will greatly help to us make the sandbox more closely aligned with the CDR ecosystem.

We have logged the issue and will include a fix in a future release.

**Comment by CDR-AndrewG** [comment]
Hi @perlboy,

This issue has been resolved in our latest Sandbox release.
