### ISSUE TITLE
Redirect URL Update Failed for software product "PDMQAYodlee"

### ISSUE THREAD

**Issue by psharma211** [ConsumerDataRight/sandbox#36]
**Describe the bug**
Redirect URL Update Failed

We are seeing below error while we are trying to add redirect url for PDMQAYodlee software product. Could you please help us to check on the same and also confirm if there is any limitation on number of redirect url that can be added for each software product id?

**Screenshots**
![errorscreen](https://github.com/ConsumerDataRight/sandbox/assets/113500406/4a3d9351-f888-46a3-a871-fd73ee2702aa)

**Comment by psharma211** [comment]
@CDR-DavidR to review and share some update

**Comment by CDR-HansenS** [comment]
Hi @psharma211, thank you for logging this issue. We have added this as a ticket for the team to look into and fix for a future release. Just for some additional information, can I confirm you are using Chrome browser?

Thank you.

**Comment by CDR-HansenS** [comment]
@psharma211 - After a quick review from the team, the SUM of the URI has a 2000 character limit which is why the error is appearing. As mentioned, this has been logged for further analysis in our backlog.

Thank you.

**Comment by CDR-HansenS** [comment]
Hi @psharma211 - Confirming this error was because of the URI 2000 character limit, we have released an update to Sandbox yesterday to display a more user friendly error rather than "Server error occurred". Please ensure that your URI redirects has less than 2000 characters to avoid this issue.

**Comment by CDR-HansenS** [comment]
Hi @psharma211 - As per above, the error you faced was related to the URI being over the 2000 character limit. We have made a change in Sandbox so the error message now reflects this to make it clearer.
