### ISSUE TITLE
Sandbox IDP incorrectly requires client_id parameter

### ISSUE THREAD

**Issue by perlboy** [ConsumerDataRight/sandbox#4]
**Describe the bug**
When requesting a token from the Sandbox register the identity server is _incorrectly_ requiring `client_id` at the token endpoint.

**To Reproduce**
1. Submit a well formed OAuth2 token request without `client_id` form parameter
2. Auth server will reject with `invalid_client`
3. Submit same request including `client_id` form parameter
4. Auth server returns tokens

_Example Walkthrough_

JWT
```
eyJraWQiOiJZcHZEY3dnU0JtMzJEYUVERmd2eThEemoyNnlpTG93d3lGeUVDZHFSajhVIiwiYWxnIjoiUFMyNTYifQ.eyJzdWIiOiJBQURDRDc1OC0xRDFELTQxRTYtQThCNi1DNEE2NEZBRUZDQkMiLCJhdWQiOiJodHRwczpcL1wvc2VjdXJlLmFwaS5jZHJzYW5kYm94Lmdvdi5hdVwvaWRwXC9jb25uZWN0XC90b2tlbiIsIm5iZiI6MTY1OTgzMjIxOCwiaXNzIjoiQUFEQ0Q3NTgtMUQxRC00MUU2LUE4QjYtQzRBNjRGQUVGQ0JDIiwiZXhwIjoxNjU5ODM1MjIzLCJpYXQiOjE2NTk4MzIyMjMsImp0aSI6IjlkZjViMDMxLTkxNDEtNDAyYS1iMDE4LWFhMTQ4ZDk5YTQ3MiJ9.e4oSh2FZNV-5tBt4fA0lzHImBq8RF7W3xQZz0FN05mcX5ZK9ycDd10IKwwi_jnq9u5-PIjNdCUI4O71vVYC9rre3wHw3_5PmODm0zzFM9iHZb9YMn2jRkPooe45zC1vcyNocVQv60ELqnZ1DTj5X0yQUwc4E1z_zazebejLgLQHdZja9NXrxD1J9SilHvIUpf7qbKkcTUztEorgR09xLKQiWC0sc5ZlnKcA5offamsRnoDIa1txhsfJEJ3trUNneu011qVVS-STsD96k2RvA8xjwXE0118ZCQsyMCSPQpUt5nMaQwFM2wqoBmuSuTZLBzKNYhXKyFyFwx3nwkFGhTw
```

Functional (incorrectly):
```
% curl --cert cdrsandbox1.crt --key cdrsandbox1.key -k -X POST -d "client_id=AADCD758-1D1D-41E6-A8B6-C4A64FAEFCBC&grant_type=client_credentials&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&client_assertion=$ASSERTION&scope=cdr-register:bank:read" https://secure.api.cdrsandbox.gov.au/idp/connect/token
{"access_token":"xxx","expires_in":300,"token_type":"Bearer","scope":"cdr-register:bank:read"}                                                                                                                                         
```

Non-Functional (incorrectly):
```
% curl --cert cdrsandbox1.crt --key cdrsandbox1.key -k -X POST -d "grant_type=client_credentials&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&client_assertion=$ASSERTION&scope=cdr-register:bank:read" https://secure.api.cdrsandbox.gov.au/idp/connect/token
{"error":"invalid_client"}    
```

**Expected behaviour**
The `client_id` parameter in the request is _optional_ and, if supplied, should be verified against the assertion.

**Screenshots**

The Standards mention `client_id` _within the assertion_ **only**:
![image](https://user-images.githubusercontent.com/4291448/183270335-212e4e39-552d-498d-9262-a18fd36dd5a4.png)

The Standards also include the `client_id` in the non-normative example. This is _not_ a specification, it is a **non-normative example**.

**Additional context**

The referenced part of the OpenID specification refers to OAuth.JWT and OAuth.Assertions:
![image](https://user-images.githubusercontent.com/4291448/183270471-8b5cadec-7876-4a1b-b83f-f6c9f2f745f9.png)

The relevant section of these sub documents is [4.2 Using Assertions for Client Authentication](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-assertions#section-4.2) which specifies this as optional:

> client_id  **OPTIONAL**.  The client identifier as described in [Section 2.2](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-assertions#section-2.2) of OAuth 2.0 [[RFC6749](https://datatracker.ietf.org/doc/html/rfc6749)].  **The "client_id" is unnecessary for client assertion authentication because the client is identified by the subject of the assertion.**  If present, the value of the "client_id" parameter MUST identify the same client as is identified by the client assertion.

**Comment by CDR-AndrewG** [comment]
Hi @perlboy,

Thank you for getting in touch with us to raise this issue. The information provided and notification of the issue will greatly help to us make the sandbox more closely aligned with the CDR ecosystem.

We have logged the issue and will include a fix in a future release.

**Comment by CDR-AndrewG** [comment]
Hi @perlboy ,

It looks like this is the intended behaviour defined in the Consumer Data Standards. The Sandbox Register follows this section of the Consumer Data Standards where `client_id` is listed as a required parameter. Please let me know if there is something I am overlooking.

![image](https://user-images.githubusercontent.com/89497569/185541646-7eaa2d29-0632-43b5-b2c5-e118cd130f47.png)

**Comment by perlboy** [comment]
@CDR-AndrewG that's interesting because the Standards also state:
> Authorisation Servers MUST support the authentication of clients using the private_key_jwt Client Authentication method specified at [section 9](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) of [[OIDC]](https://consumerdatastandardsaustralia.github.io/standards/#nref-OIDC).

Which links to [OAuth Assertion Framework](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-assertions#section-4.2) which includes:

> client_id
>       **OPTIONAL**.  The client identifier as described in [Section 2.2](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-assertions#section-2.2) of
>       OAuth 2.0 [[RFC6749](https://datatracker.ietf.org/doc/html/rfc6749)].  The "client_id" is unnecessary for client
>       assertion authentication because the client is identified by the
>       subject of the assertion.  If present, the value of the
>       "client_id" parameter MUST identify the same client as is
>       identified by the client assertion.

On this basis it appears the Data Standards seem to be changing the definition of the underlying RFC. As such I've created a [change request in standards-maintenance](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/535) to either remove the OIDC line or remove the redefinition of what parameters are required.

I'll see what I can do about adding this optional field into our client and see how far we get from there.

**Comment by CDR-AndrewG** [comment]
Hi @perlboy ,

Thank you for the response. We'll keep track of the change request logged and make any required changes to the Sandbox as a consequence.
