### ISSUE TITLE
CDR Sandbox PAR call failure

### ISSUE THREAD

**Issue by psharma211** [ConsumerDataRight/sandbox#40]
We have identified an issue with the par call for all clients connecting to the bank. This issue is currently blocking our testing. I kindly request that you investigate this matter at your earliest convenience. We have raised a request to track the issue.

Request:
https://dh-bank.secure.idp.cdrsandbox.gov.au/connect/par

eyJhbGciOiJQUzI1NiIsImtpZCI6IjE2MTM4ODMzNjkzMDEzNjI1OTg4NDk0OTAyODcyMzkyNTQyNTcwIn0.eyJpc3MiOiI3MWJjMDBlOC1jZmVhLTQ3YjQtYWFmMy00YTA3MzRiYjA5NGYiLCJhdWQiOiJodHRwczovL2RoLWJhbmsuaWRwLmNkcnNhbmRib3guZ292LmF1IiwicmVzcG9uc2VfdHlwZSI6ImNvZGUiLCJjb2RlX2NoYWxsZW5nZV9tZXRob2QiOiJTMjU2Iiwibm9uY2UiOiJNVGN5T1RFMk1ESXpNakl5T1E9PSIsImNsaWVudF9pZCI6IjcxYmMwMGU4LWNmZWEtNDdiNC1hYWYzLTRhMDczNGJiMDk0ZiIsInJlc3BvbnNlX21vZGUiOiJqd3QiLCJjbGllbnRfYXNzZXJ0aW9uX3R5cGUiOiJ1cm46aWV0ZjpwYXJhbXM6b2F1dGg6Y2xpZW50LWFzc2VydGlvbi10eXBlOmp3dC1iZWFyZXIiLCJuYmYiOjE3MjkxNjAyMzIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgYmFuazphY2NvdW50cy5iYXNpYzpyZWFkIGJhbms6dHJhbnNhY3Rpb25zOnJlYWQgY29tbW9uOmN1c3RvbWVyLmJhc2ljOnJlYWQiLCJjbGFpbXMiOnsic2hhcmluZ19kdXJhdGlvbiI6MzE1MzYwMDAsImlkX3Rva2VuIjp7ImFjciI6eyJ2YWx1ZXMiOlsidXJuOmNkcy5hdTpjZHI6MiJdLCJlc3NlbnRpYWwiOnRydWV9fSwidXNlcmluZm8iOnsiZ2l2ZW5fbmFtZSI6bnVsbCwiZmFtaWx5X25hbWUiOm51bGx9fSwicmVkaXJlY3RfdXJpIjoiaHR0cHM6Ly9hdW5leHRnZW5vY2MueW9kbGVlLmNvbS5hdS9vYXV0aGNsaWVudC9nZXRPQXV0aEFjY2Vzc1Rva2VuLmRvIiwic3RhdGUiOiJBazIxWW1KLWJUNmY4anFBckNnV3kweUt6LWFYSUlaSzBDZU5yUjhOYjRfU1NTIiwiZXhwIjoxNzI5MTYyMDMyLCJpYXQiOjE3MjkxNjAyMzIsImNvZGVfY2hhbGxlbmdlIjoiUXdlTXBFTkZsZXhCZkZBbkZzR1YxVFFKbkh6ZjhSdzhTSzg1d3lTYjFGZyJ9.OvgmzQz8lOz53Grs3DJTOoW67nshz3CXBOks04tIdC_ystzdfx08RruWI3QtPUgr8o5ZuquY0gSrPL1v8U6Hdy7vlui79Fq8y6_SH8XgVOKO_bXATh9naQ6sog2AlJM5dxY3FuiA9HJKkS_AX1uQ73iKR7EmcGZP_vKqiosxhSmZa9Z7mBMcwsopwRRHyLOktkT630CENhAzq670HJO95401jx2S-YrAQOey3TqV2PtikSXNnAX6BBvL4-29_eBs1G-3hteiJNu46u_OpEnmQTbEl9TmoINj-_BQORqubDu8i7OFDm_bXqly_6SDYb6WyEoXrFf7NfqYYuMCB_9Jpw

Timestamp: 17 Oct 2024 03:17:12 PDT 
Response Headers : [Date: Thu, 17 Oct 2024 10:17:12 GMT, Content-Type: application/json; charset=utf-8, Transfer-Encoding: chunked, Connection: keep-alive, Strict-Transport-Security: max-age=31536000; includeSubDomains]

Response Code : 400

Response Message : Bad Request
Response: {"error":"invalid_request","error_description":"ERR-GEN-007: Invalid redirect_uri for client"}

**Comment by CDR-HansenS** [comment]
Hi @psharma211, thank you for raising your issue with us. Our team has had a look into this and it appears that the 'redirect_uri" used in the attached PAR request JWT, is not in the list of redirect uri's for the current registration (Sandbox Data Holder Banking).
Can you try to perform a new registration (DCR) with this redirect URI included in the request?

Please let us know how you go.

**Comment by psharma211** [comment]
Hi @CDR-HansenS , Thank you for your quick response.

We would like to clarify that we have already registered, and everything was working 
correctly until yesterday. The issue has arisen suddenly, without any changes on our end. I am attaching a screenshot of the URIs from your portal for the software product ID: d163b31d-affa-4e11-81c5-1196f615d33b.
![image (8)](https://github.com/user-attachments/assets/0eafd812-ef82-4e22-9622-750a114a9a90)

I will share the SSA response separately via email to confirm that the registration is already in place. 

We kindly request your further analysis on this matter to help us identify the root cause of the issue.

Thank you for your assistance!

**Comment by psharma211** [comment]
Hi @CDR-HansenS , Thank you for your quick response.

We would like to clarify that we have already registered, and everything was working correctly until yesterday. The issue has arisen suddenly, without any changes on our end. I will share the SSA response separately via email to confirm that the registration is already in place.

We kindly request your further analysis on this matter to help us identify the root cause of the issue.

Thank you for your assistance!

**Comment by psharma211** [comment]
I have shared the password protected file over mail for the SSA response. Please send a separate mail for the password

**Comment by psharma211** [comment]
@CDR-HansenS  Can you please share an update?

**Comment by CDR-HansenS** [comment]
Hi @psharma211, Sorry I only just saw Divya's email. We are currently in a two day planning session, we will have a look ASAP.

**Comment by psharma211** [comment]
Hi @CDR-HansenS ,

Thanks for the clarification provided. We have updated the registration. It was working fine now.
