### ISSUE TITLE
LegalEntity status not returned in mock-register API response

### ISSUE THREAD

**Issue by natepage** [ConsumerDataRight/sandbox#5]
**Describe the bug**
When using the docker containers from https://github.com/ConsumerDataRight/mock-register, requesting the list of DataHolderbrands, the response doesn't contain the `legalEntity.status` field.

**To Reproduce**
1. Request an access_token from `https://mock-register:7001/idp/connect/token`
2. Request list of DataHolderBrands from `https://mock-register:7001/cdr-register/v1/banking/data-holders/brands`

**Expected behaviour**
According to the docs from https://consumerdatastandardsaustralia.github.io/standards/?examples#get-data-holder-brands, we are expecting to receive this field in the response.

**Comment by CDR-AndrewG** [comment]
@natepage Thank you for getting in touch. Can you confirm what value you are passing through to the x-v header for Get Data Holder Brands?

**Comment by natepage** [comment]
@CDR-AndrewG Thank you for your response. I wasn't explicitly sending this `x-v` header so it was defaulting to 1. I've explicitly set it to `x-v: 2` and now I can see the status of the legalEntity coming back in the response. 
Looks like this issue is resolved 😄

**Comment by CDR-AndrewG** [comment]
@natepage Thank you for the update. Good outcome. The same behaviour is present in each of the register APIs. eg x-v will default to 1 if not supplied.

In the call yesterday it sounded like there was another issue that needed looking into. I'm happy to help if there are other issues present. Raise an new issue if required and we'll look into it.
