### ISSUE TITLE
500 on DataHolder register

### ISSUE THREAD

**Issue by natepage** [ConsumerDataRight/sandbox#6]
**Describe the bug**
We are receiving a `HTTP/1.1 500 Internal Server Error returned for "https://dh-bank.secure.idp.cdrsandbox.gov.au/connect/register".` when trying to register our SoftwareProduct with the Sandbox DH `Sandbox Data Holder - Banking (cf217aba-e00d-48d5-9c3d-03af0b91cb80)`.

**To Reproduce**
1. Fetch SSA
2. Fetch `Sandbox Data Holder - Banking (cf217aba-e00d-48d5-9c3d-03af0b91cb80)` details
3. Fetch DH OIDC configuration from its infosec URI `https://dh-bank.idp.cdrsandbox.gov.au/.well-known/openid-configuration`
4. Generate JWT based on requirements from [ClientRegistration](https://consumerdatastandardsaustralia.github.io/standards/#client-registration)
5. Send `POST https://dh-bank.secure.idp.cdrsandbox.gov.au/connect/register` with JWT from step 4 as body, `application/jwt` as ContentType, `application/json` as Accept headers, and using the client certificate for the SoftwareProduct for mTLS
6. Get 500 response back

**Expected behaviour**
Receive a successful response from DH register endpoint with `client_id`

**Additional context**
I wasn't sure if it was ok to share a generated JWT here to help understand the issue, because I believe it's not a Sandbox problem but something we are not doing right in our implementation 😄 
If it's ok to share it here, I'm happy to drop one in a comment.

I'm also open to other ways of communication if github issues become challenging to understand the full picture.

**Comment by CDR-AndrewG** [comment]
Hi @natepage,

I've had a look through the logs. I can't be certain this error is occurring for your request but it looks similar. This error occurs in  the [JwtInputFormatter](https://github.com/ConsumerDataRight/mock-data-holder/blob/main/Source/CDR.DataHolder.IdentityServer/Formatters/JwtInputFormatter.cs) when processing the SSA received in the `register` request.

If this does not help, can you please re-attempt the registration request anytime from Monday morning next week and let me know the date and time the failure occurred?

```
Error processing the SSA JWT "IDX12741: JWT: 'System.String' must have three segments (JWS) or five segments (JWE)." "   at System.IdentityModel.Tokens.Jwt.JwtSecurityToken..ctor(String jwtEncodedString)
   at CDR.DataHolder.IdentityServer.Models.SoftwareStatement..ctor(String jwtEncodedString) in /app/CDR.DataHolder.IdentityServer/Models/SoftwareStatement.cs:line 11
   at CDR.DataHolder.IdentityServer.Formatters.JwtInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding) in /app/CDR.DataHolder.IdentityServer/Formatters/JwtInputFormatter.cs:line 48"
```

**Comment by natepage** [comment]
Hi @CDR-AndrewG 

Thank you for that, it was me yes 😄 I was sending the SSA raw data as an array instead of its original JWT form, I've fixed this and was able to register successfully and have a `client_id`.

I'm now trying to go through the consent flow by request the PAR endpoint, but I keep on getting a 400 Bad Request with the following payload: `{"error":"invalid_request","error_description":"Invalid JWT request"}`.
To get to this point I have:

- Requested an access token for the DH endpoints with the `cdr:registration` scope and using the previously obtained `client_id`,
- Generate a client assertion
- Send a request to DH PAR endpoint with the `client_id`, `client_assertion`, `client_assertion_type`, and `response_type`

**Comment by CDR-AndrewG** [comment]
Hi @natepage ,

Nice to hear that helped.

This is the error I'm seeing in the logs

```
Authorize validator returned error "invalid_request" "Invalid JWT request"
PushedAuthorizationRequestValidationFailureEvent { Check: PARInvalidRequest, Category: "Request", Name: "Invalid Pushed Authorization Request", EventType: Failure, Id: 991434, Message: null, ActivityId: "0HMJUB0ANHQ90:00000002", TimeStamp: 08/21/2022 12:10:42, ProcessId: 9, LocalIpAddress: "xx", RemoteIpAddress: "xx" }
```
It occurs here in the [ProcessAuthoriseRequest method](https://github.com/ConsumerDataRight/mock-data-holder/blob/main/Source/CDR.DataHolder.IdentityServer/Services/PushedAuthorizationRequestService.cs).

I can't be certain without the request but it looks like this is the area where the validation fails. [ValidateAsync](https://github.com/ConsumerDataRight/mock-data-holder/blob/main/Source/CDR.DataHolder.IdentityServer/Validation/PushedAuthorizationRequestValidator.cs).

```
request.Raw = parameters ?? throw new ArgumentNullException(nameof(parameters));

var jwtRequest = request.Raw.Get(OidcConstants.AuthorizeRequest.Request);
if (!jwtRequest.IsPresent())
{
    return Invalid(request, description: "Invalid JWT request");
}
```

Let me know if that lines up with what you are seeing.

**Comment by natepage** [comment]
@CDR-AndrewG Thank you for this, I wasn't constructing the PAR request properly.

I'm now creating a JWT and pass it as the `request` parameter, however I'm now getting this: `{"error":"invalid_request_object","error_description":"JWT validation error"}`.

I'm assuming it's failing to verify the JWT itself before actually validating its payload. I'm using the client certificate I've issued from the sandbox portal to sign this JWT (private JWK to sign it, public JWK to expose via my JWKs endpoint), is that correct? Or am I missing something here?

**Comment by CDR-AndrewG** [comment]
Hi @natepage,

It looks like the `aud` field is missing from the claims list in the JWT. The [Registration Request using JWT](https://consumerdatastandardsaustralia.github.io/standards/#client-registration) section found here has some more information on the JWT.

A missing `aud` field is being picked up by the `ValidateJwtAsync` method of the [CustomJwtRequestValidator](https://github.com/ConsumerDataRight/mock-data-holder/blob/main/Source/CDR.DataHolder.IdentityServer/Validation/CustomJwtRequestValidator.cs).

```
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10206: Unable to validate audience. The 'audiences' parameter is empty.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at CDR.DataHolder.IdentityServer.Validation.CustomJwtRequestValidator.ValidateJwtAsync(String jwtTokenString, IEnumerable`1 keys, Client client) in /app/CDR.DataHolder.IdentityServer/Validation/CustomJwtRequestValidator.cs:line 212
   at CDR.DataHolder.IdentityServer.Validation.CustomJwtRequestValidator.ValidateAsync(Client client, String jwtTokenString) in /app/CDR.DataHolder.IdentityServer/Validation/CustomJwtRequestValidator.cs:line 114
```

**Comment by natepage** [comment]
Hi @CDR-AndrewG correct, I don't have such field in the Request object I'm sending to PAR, could you please tell me what value should I be using? The issuer from the DH OIDC configuration?

**Comment by CDR-AndrewG** [comment]
@natepage Yes, that is correct. It is the issuer returned within https://dh-bank.idp.cdrsandbox.gov.au/.well-known/openid-configuration.

`"issuer":"https://dh-bank.idp.cdrsandbox.gov.au"`

**Comment by natepage** [comment]
@CDR-AndrewG once again thank you, I've managed to obtain a `request_uri` from the PAR endpoint. However, when trying to access the authorization endpoint using it I get an error. Here is some info:

- request_uri: `urn:mdh:3b737970-715a-4df4-9b9b-2fb60a1b08e9`
- authorization URL: `https://dh-bank.idp.cdrsandbox.gov.au/connect/authorize?urn%3Amdh%3A3b737970-715a-4df4-9b9b-2fb60a1b08e9`

**Comment by CDR-AndrewG** [comment]
Hi @natepage, nice to hear progress is being made.

This is the error occurring in the Data Holder:
`client_id is missing or too long
AuthorizeRequestValidationLog { ClientId: null, ClientName: null, RedirectUri: null, AllowedRedirectUris: null, SubjectId: "anonymous", ResponseType: null, ResponseMode: null, GrantType: null, RequestedScopes: "", State: null, UiLocales: null, Nonce: null, AuthenticationContextReferenceClasses: null, DisplayMode: null, PromptMode: "", MaxAge: null, LoginHint: null, SessionId: null, Raw: [("urn:mdh:3b737970-715a-4df4-9b9b-2fb60a1b08e9": "")] }`

`Authorization Error - error: "invalid_request", error_description: "Invalid client_id"`

It looks like the request being made the the authorize endpoint is incomplete. This is an example taken from the Sandbox Data Recipient running in the CDR Sandbox:

![image](https://user-images.githubusercontent.com/89497569/186349769-e5a630c0-3cd0-4690-a695-963d9aeab32a.png)

The code running in the CDR Sandbox - Data Recipient to initiate PAR can be found here in the [PARController](https://github.com/ConsumerDataRight/mock-data-recipient/blob/main/Source/CDR.DataRecipient.Web/Controllers/ParController.cs).

The authorisation process followed by the Sandbox Data Holders and Sandbox Data Recipient is specified in the [standards](https://consumerdatastandardsaustralia.github.io/standards/#authentication-flows) and in [OIDC](https://openid.net/specs/openid-connect-core-1_0.html#AuthorizationEndpoint).

**Comment by natepage** [comment]
@CDR-AndrewG thank you, I will update my logic, but I thought that the point of using the PAR endpoint and sending the `request_uri` parameter to the authorization endpoint was to use a single query parameter, why do we have to send the other parameters as part of the query as well?
Is every data holder going to behave the same way?

**Comment by natepage** [comment]
@CDR-AndrewG I've updated the logic and now trying to request the authorization endpoint:

```
https://dh-bank.idp.cdrsandbox.gov.au/connect/authorize?client_id=2195d069-25cd-411f-acbb-3c4effc19bb9&scope=openid+profile+bank%3Aaccounts.basic%3Aread+bank%3Aaccounts.detail%3Aread&response_type=code+id_token&request_uri=urn%3Amdh%3A39f98239-c7ae-4045-9ee6-3553427a6802
```

However this redirects straight back to my callback endpoint with the following: `/redirect#error=invalid_request_object&error_description=Invalid%20JWT%20request` and I'm not sure why...


Am I supposed to provide a JWT request object to the authorization endpoint? I'm not sure how to do this

**Comment by CDR-AndrewG** [comment]
Hi @natepage,

No problem, DCR and PAR are complex processes. Every time I look into it I learn something new. This exchange has increased my understanding :) 

To help to get through the process, I recommend looking into these areas:

- [Sequence diagrams showing the process](https://cdr-support.zendesk.com/hc/en-us/articles/5300325565199-Consent-sequence-diagrams)
- [Code example of the Sandbox Data Recipient](https://github.com/ConsumerDataRight/mock-data-recipient/blob/main/Source/CDR.DataRecipient.Web/Controllers/ParController.cs). In the Sandbox Data Holder PAR Controller we - Build the authentication request JWT; Call the Data Holder PAR endpoint, passing in the request JWT; Build the Authorisation URL for the Data Holder passing in the request uri returned from the PAR response. The next step here would be to clone the git repo and step through the code. A Register and Data Holder can also be cloned to run a mock ecosystem in your local environment. The [help files](https://github.com/ConsumerDataRight/mock-data-recipient/tree/main/Help) have some steps regarding running the code locally, in docker containers or a combination of both.
- These is the requirements we are following when calling the authorise endpoint. See the [Authentication Request section](https://openid.net/specs/openid-connect-core-1_0.html#AuthorizationEndpoint) .

**Comment by CDR-AndrewG** [comment]
Hi @natepage,

Closing this issue as there are no open questions to look into. Please feel free to reach out again in the future.
