### ISSUE TITLE
SSA call for our newly created Software Product(4eb9db35-9033-49ee-9cdc-4d73de314507), with SMDHB (cf217aba-e00d-48d5-9c3d-03af0b91cb80) is failing

### ISSUE THREAD

**Issue by gvharibb** [ConsumerDataRight/sandbox#7]
**Describe the bug**
SSA call for our newly created Software Product "Test1" (4eb9db35-9033-49ee-9cdc-4d73de314507), with SMDHB (cf217aba-e00d-48d5-9c3d-03af0b91cb80) is failing

**To Reproduce**
Below is the curl command that was executed
curl --location --request POST 'https://dr.cdrsandbox.gov.au/ssa' \
--header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
--header 'Accept-Language: en-US,en;q=0.9' \
--header 'Cache-Control: no-cache' \
--header 'Connection: keep-alive' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Cookie: .AspNetCore.Cookies=CfDJ8LXiheCf8p5Lub07DtL2d2sZoPUBbUfJ4sBmygEOK8xHai8H646q4AHxEGrFtC-6kMVSHwFR7wziu_ZAzCEav2UXQCFZfYzPJa5oQtDc6bqdWsWsQ1TBFhcB5UbgrbCwD_lGvoz-bbdm59oM_ZUBx26rp6pCocjetwIr7fD5bbpqOT82oo6weBxqmM8a5Uw7yaI-aGHo3ckbfIx3CbwzxvXSCXd0zldLWCfjL_q4psJvoQNWB7cQFCuUjj4zlReSJKL09U1mrxZYxOZXGCucBBRPiS7Y4LtAEeRbEXM61CDnYqHyKxTa18ixfMD_Ilp3NVaDxmyCGMZns2WTFnGpkyfB8sBqInsvQYkDV05NgnyROMVD8RwM00dsVu2jcb0o5PrqISFT2dV8P4tL_U84FUH8_qhFd4qfp475NBWVP7I56ajiiGSvIh0sMf6sAg1DbiLeAJ4FsCfNwZo-Ea6Trb000l-Ml7FY7_CncCTViKAk8KEgJY3KLmzmEXerDSzzjtesIbyUYzTVTWyUAq64VtgiDQsKlTt_PklUjch_DhQLIa8tyKSfxKRRDzdYC3WeNuU0RV_G5I6A5BCyD7rnjefnEdb2_zFMf23XmdsKc3CihkBFAVANx5WNTIOvcfXGmLYDtD76ulaQpuaXJ423gVwN8omRMXXgBWnSGFdHp16gX585odsbe2TLW4FlzWRRPbKqVmWcdsMiYyZO-0NvRngvB2YW02xN2ZMUUlvJNiXv5eGz06sCMDqG_FXdNjlRfue7CopHWxovCMydNwNiGPN9TZmXE6--y_krySJ5Iun2UxM2fKHXFjG3Jdcb7FAIQqeigXhV3OsXsFblhhNzKrvdluSJuR-pBHn2S5YNGfi1EmaCYD-wtcHKM-Oxz_N4vrV5gnq0go5dvtmpxZc53nTzzdFdBxnnsmlPnOFS5mhLF-bxVFOEHZVezPXUpZpK4S9xsUQRoBWMCeBUdJCXCh1wDSGjlJuCTPgXdNAbjDkg6feefujMyb_d470w7HIGYdt4MPNd26aLmg6shyVU8Exo36CessRtS_N5-jNnhFl5Bri57Fkhz6z94cGe9ozmxz9JFazMQeVbiTvOT8aBUARhefwyNo4hMuYgOYBpDDUzwK4gFM86RAjgyCKrQqlnO2emdKoVgW8kOJpd5wNG7NE8C6xZGhwzWJ7Fc8twJfo7kx0Eo4-ZPH5IvmJq2oITtQ4gdb7f062Y64EleAorLKXjTct0qa636O5VvsPi1EELkKqo7chSe3i-lZXgsjEo7xatucz74WdPwdkJctqhmHIIcvcEAjrF1N_kIJYyOISyq8elmX4DOjm679FG8zfBz7CcnTg11-JTCucA4XQEjLWmBHlKVExd0n73b8AinUQXBVbAnzO_QqIRa85KcmVCIHbz7Vm0J8uIoGYZDqLDZHAzPUa4VI7_SzmqS0ERYO03sYz5Q4b7xXnMrHbi3D0TwKLO4YR-bRL2c56UB7-QOQpqyXxocUgfSkiNZtlvYe_1NSj8ULNrGJbaIAO_cl4NY3wWd1dRtYWjjnvt5vuEdLcgEQW9KW9k6_jX2HliIKrAUB7tRweHb5wXaC8wIEAuWOJDbSxJws7jt0Q4M59ZS9GZ7oTLLWdPmmm9c5Vvd4YOrWHM8yH1B7F0tIefAiFagsTjVrsTzBvPmlp15ccoZ5cX-Ui7BEACTvF7_oB6Tnav18JxAMSu5YKYhyYno_v9rlqXsSnl8bsPXCf95ass5LCMCjqxbJGv1R6y0FRvJ-V0z82YHt8kMYIEbqk7eDSBJxDvKwSRWpS1-e0uc-duUTaEg5PQDHUrst18VSY2fZp1O1i47cmG9OdzXfbWL0NcyPkDOqPJ6-YekPJyfXmpVoTMqhNv45DBQEdP5TS40pFZGsdhaxJZn8r8ZL3UfyLXhMAHH91tMKpmVtRhnKpqb1gRBFuaL5fztCG4jS3ESi_ZDCKpSS1uK1Pn9U6Up1pt14mnLaQpA--7qhYzLNWJa1nTzcHCiS5YmQPpT_5NtniX7UZ-I5fsVlwuE5ju0cFaidTO74JmklU0Sv8S7sYuOSclKElh8qiW2sT7aZXBM3iioGC3QgBXm2kkl1WHtd2CpBQonNb-dgVQVht709xI1ZUJxdnMILOaBX3RA5-x0wzO-dVGWcjjic9v8BfcDp-5xunGQFJvSVaVsERSDxM_ZJMBCaOVX4iE-ZFgtwqU-T1lwWAzUA8m0sXmeRFPaBBVWI5KqLePCtu3Q7N3KeVpkjv5CdedPx2foggj51SWyJBXtYkXES4MTGync4jEvujueHQ5VS03F1uGo3-aOw_JpGcCwIpEld9-We5wJaNloR-RZdpxOkIbU1SYouOsgsNfftBoIJa1AsN436hdNGyKjPQmqhFrlqjvsrhzi3a4JP2vZa8YUWZNhX72jR6AKEU9hqrTo2eDvzs2wQaPcHHIMI6-sPF35wYNJTY6W-M62vQ7VvoU_cS-BQkSK4-KMGlp-iWylIvbBx7Qe0HTDnjyP3jpvSQRkUnNbM1T4O9TKz922YHqtuV-eJ5Y2mx0xESBkWhTyCFi2VkttYqx-lY9_zlWjqdOPwlRETKiPBEYUym2NbR21Wx_mbZWJ5sLJhVNuLDj6YuAOEC3Wcu-Icn9-fTiiAxkjJXqIIh1r6_dC_0k0yS6TBpStUD-7fJWe9e9zZ7OvS2Fpst842MlSgsA1DfkTPMgU3UAeKfKzg3k9Oj47QtRD12wK2N8jR4cRUykvY5iSr_pNDR3kQddFQI4pPdnoCVwOS4cx__wW8FixhLA3PkvfoiwMRRTDcdKoahpLaBKIiNqC1e5tQsciFeu3ktEqkuTMk6mv4P1Xe_2a3_WgAsWPPFMRUWPQtpjBl0eqT5vcn4j2xDa9L6yBDgdk_ffUesq3ni4ekUxwANa-Ix3WqYQCuL3NNFkgbyaOkEDOAP41c1Z31kIoK0k8NRXnPGkbxMeVkX8SA_mB2czg0E-Ki5DqjtG5MZhNNbI1Prd4KOv9ww0R96sDN8W142Y2xbHu4n6Xn2gytssR3OkHUroQINIWJKxhxacsflDhMVVlvBIzKCAPlpbWkg_BcZ2RUfn77RMvFLxJm6bxjZiAREm3w4yeWuAp2K5fzCi_GSwkZHjwJQZ5F5KTDEKaz_Yy4r340tNyqTboUAHJT02FkWHKMAFPSnfs0kaUcl6qQF-hxmskzhIYzZAvrUYaIEv6StXJTzTb22Axoc6chu4l3VEpHB9m2YRtiQK0--M8jV5f_8vzglqq_gM6vh5-udcOegPoYREN0zu79Wt9gmrjBsFXH5SAzcEKYdgOewTi0QSN6W6zLNCDxHcrbmkNC7ZPPZehmz9SAppOKn7ACjrJv4dQUndgG-t3P8u9P9CBJLdWEZdOKC4oXuvVw_RNcC_ekDipOSrhxsT0yhssiCm2hXX9B4G4X3_43Kf6u4zbr-ZlfOov5yuTxz1CTKfIxeAqBQSGAkpdjW8cJoJTEQG83voUuDoyzsONOf67MigvBA6jo670Rq1CARsftW7waYQ4Yw-VJCXOLblc5JwREH7MLiNaIRgi9N_Dq1zWmAlpYWNAr-6XaT-EHofF6A7CCwDJoxY8nHQpsfEAvMB4sRfGByqrstHINvC0aDOjaC6zUIevT1znE8yfAoPUtTMTyrXujrsVb3vrFe2fAJXapp5-5tWA1LdLBza4nbtQqmInMCNNMGAo-E0jBJdvAPiXlR-vz71VfWJr1ChJ0dAeaA__LQYhsfzVqjtcBB8erAT42R2WBVtFHroFNnGXNX4djHmA30; .AspNetCore.Antiforgery.IhO7x7tiR54=CfDJ8LXiheCf8p5Lub07DtL2d2tD580d79zyZrk1u_07BqXOZf7dRep2Dn3HhWk4rabsnUO4QQ45jOTATSRBR2ZTQIHDqI0PMbrCVmOF5jrbPe0wYyeSt_XqMyGdcb7c_Ipz1AlIYXussMMJUfgZiiSCAOQ' \
--header 'Origin: https://dr.cdrsandbox.gov.au' \
--header 'Pragma: no-cache' \
--header 'Referer: https://dr.cdrsandbox.gov.au/ssa' \
--header 'Sec-Fetch-Dest: document' \
--header 'Sec-Fetch-Mode: navigate' \
--header 'Sec-Fetch-Site: same-origin' \
--header 'Sec-Fetch-User: ?1' \
--header 'Upgrade-Insecure-Requests: 1' \
--header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36' \
--header 'sec-ch-ua: "Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'sec-ch-ua-platform: "Windows"' \
--header 'sec-gpc: 1' \
--data-urlencode 'Industry=0' \
--data-urlencode 'Version=3' \
--data-urlencode 'BrandId=ffb1c8ba-279e-44d8-96f0-1bc34a6b436f' \
--data-urlencode 'SoftwareProductId=4eb9db35-9033-49ee-9cdc-4d73de314507' \
--data-urlencode 'get-ssa=Get+SSA' \
--data-urlencode '__RequestVerificationToken=CfDJ8LXiheCf8p5Lub07DtL2d2vEg85oMmsXmo_ck2uBJzODEw3tXa4gXD-KWYmGDy41X7IRVDTExlzv40keT5EtOzFii-VOQYxWMiLWBOeJNReajETQkaIdtl6ip53AHrFm2jNm89UzjaveU46kTV9meSIEvjYZwFECX0pLXSn9De2BaOnGEsROPneALiXnnpjyxw'

**Expected behaviour**
Valid SSA should be returned

**Screenshots**

**Additional context**

**Comment by CDR-AndrewG** [comment]
Hi @gvharibb,

To get an SSA for your Software Product, make a call to the Sandbox Register using `https://secure.api.cdrsandbox.gov.au/cdr-register/v1/All/data-recipients/brands/{brandId}/software-products/{softwareProductId}/ssa`.

The Get SSA endpoint requires an access token to be presented in the call. This Sandbox Register endpoint will give you an access token - `https://secure.api.cdrsandbox.gov.au/idp/connect/token`.

The Client Certificate associated with your Software Product will need to be presented when calling the token and Get SSA endpoints. Details for acquiring a certificate can be seen [here](https://consumerdataright.atlassian.net/wiki/spaces/PT/pages/5013561/Create+and+Manage+Software+Products).

Example code for how the Sandbox Data Recipient gets an SSA can be seen in the `GetSSA` task [here](https://github.com/ConsumerDataRight/mock-data-recipient/blob/main/Source/CDR.DataRecipient.Web/Controllers/SsaController.cs).

Unfortunately, the GetSSA page seen within the [Sandbox Data Recipient](https://dr.cdrsandbox.gov.au/ssa) will not be able to get an SSA for other Software Products. Only the default values for Brand Id and Software Product Id will work on this page when hosted within the CDR Sandbox. This is due to the Client Certificate that is configured for the Sandbox Data Recipient. The Client Certificate belongs to the Sandbox Data Recipient's Software Product Id. The Sandbox Register will validate that the Client Certificate presented belongs to the Brand Id and Software Product Id given in the Get SSA request.

**Comment by gvharibb** [comment]
Hi AndrewG,

We are trying to the token call for our Software product 4eb9db35-9033-49ee-9cdc-4d73de314507. But we are getting failure response. Please find the Request and Response.

Request:
curl -L -X POST '[https://secure.api.cdrsandbox.gov.au/idp/connect/token'](https://secure.api.cdrsandbox.gov.au/idp/connect/token%27) -H 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=client_credentials' --data-urlencode 'scope=cdr-register:bank:read' --data-urlencode 'client_id=4eb9db35-9033-49ee-9cdc-4d73de314507' --data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' --data-urlencode 'client_assertion=eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiIsImtpZCI6Ijg1RTNBQTRCRTYxRTVCODkzNkMyMUQ1NzI0MEZDOUMifQ.eyJhdWQiOiJodHRwczovL3NlY3VyZS5hcGkuY2Ryc2FuZGJveC5nb3YuYXUvaWRwL2Nvbm5lY3QvdG9rZW4iLCJpc3MiOlsiNGViOWRiMzUtOTAzMy00OWVlLTljZGMtNGQ3M2RlMzE0NTA3Il0sInN1YiI6WyI0ZWI5ZGIzNS05MDMzLTQ5ZWUtOWNkYy00ZDczZGUzMTQ1MDciXSwianRpIjoiOGFjZDQ5OWQtYzE0OC00MzQ3LWE2M2YtMTk4M2MwZjUxNzk1IiwiZXhwIjoxNjYyOTY1OTc5LCJpYXQiOjE2NjI5NjIzNzl9.f74Z0Ys1_yMDZKBYpDC6LReVgOcxsoLQ6A46r92hM36KQQ1sCYlWClmuvzj5Gc34Q0HreU6n4mwzVg3hqjJn3_DlmWLJxMEKJqks8l97OdF_0H94ul-S-O1x6dUpr76LSOkMb1rtJmtY4uuSIonpjYPMqqErzXFS8FbZykFaLnGQpkuQ4xs83Kzx-Mw7oiK5wNX4akl6Pz03MRCfT2oiynaGSyWAX8mW4hhGkqBwr5wi5GVpg6g0yoXWXAeQlKwFJIvULJZuHeG2wXo47uZbZKr6aGEqtKNjrmq0wIlnNiV4ft4xcy__hV2flubcXHVDyYjz_RfSMP6OSuTkQ95xJQ'

Response: 400 bad request
{
    "error": "invalid_client"
}

**Comment by gvharibb** [comment]
We are able to make the access token call now. Post that we are getting failure in the get SSA call
Please find the error logs attached for your reference.
[sb-logfile-20220916-070636.csv](https://github.com/ConsumerDataRight/sandbox/files/9581644/sb-logfile-20220916-070636.csv)

**Comment by CDR-AndrewG** [comment]
Hi @gvharibb,

Thank you for providing the log csv. It looks like the Get SSA call has an incorrect Brand Id in the address.

`https://secure.api.cdrsandbox.gov.au/cdr-register/v1/banking/data-recipients/brands/{Your Data Recipient Brand Id}/software-products/{Your Software Product Id}/ssa`

Replace the sections in the above address with your `Data Recipient Brand Id` and `Software Product Id`. 

The `Data Holder Brand Id` can be found on the Create and Manage Data Recipient Brands page in the Sandbox.  [See here for more information](https://consumerdataright.atlassian.net/wiki/spaces/PT/pages/4948464/Create+and+Manage+Data+Recipient+Brands)

The `Software Product Id` can be found on the Create and Manage Software Products page in the Sandbox. [See here for more information](https://consumerdataright.atlassian.net/wiki/spaces/PT/pages/5013561/Create+and+Manage+Software+Products)

**Comment by gvharibb** [comment]
Thanks we are able to procced further. We have now failure in the token call, not able to download the logs for this call.

Request:
curl -L -X POST '[https://dh-bank.secure.idp.cdrsandbox.gov.au/connect/token'](https://dh-bank.secure.idp.cdrsandbox.gov.au/connect/token%27) -H 'grant_type: authorization_code' -H 'code: 849D4AEB60770B1E71236C5984A7449F6B2E0BFCF39A742F92F3303EF5B094C3' -H 'client_id: 246df974-dbc6-4d9d-9ac1-49253d51fe73' -H 'client_assertion_type: urn:ietf:params:oauth:client-assertion-type:jwt-bearer' -H 'client_assertion: eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiIsImtpZCI6Ijg1RTNBQTRCRTYxRTVCODkzNkMyMUQ1NzI0MEZDOUMifQ.eyJhdWQiOiJodHRwczovL2RoLWJhbmsuaWRwLmNkcnNhbmRib3guZ292LmF1IiwiaXNzIjoiMjQ2ZGY5NzQtZGJjNi00ZDlkLTlhYzEtNDkyNTNkNTFmZTczIiwic3ViIjoiMjQ2ZGY5NzQtZGJjNi00ZDlkLTlhYzEtNDkyNTNkNTFmZTczIiwianRpIjoiMGY1OWY0ZWUtYTRjNi00NTE0LTlmMDItYTQ5ZjhmZDljZTUxIiwiZXhwIjoxNjYzMzQwMTQwLCJpYXQiOjE2NjMzMzY1NDB9.eYnbivNpQJw7hyx_oLBsj2n3a7a15etV04PhxZF62JmT3Xi_zpZbJTOCeASnEdBMZTaPiGm0yZ3cJM7riAVUtv81ZUJAkhfNi23J7fxIVMkhdPZP3V9OeH2gK8twcohmQR7gTmcFKiGxjxHiqxR38OkfrmNoIVyOT_vHWXDTUhyRITmORu925iiFxqOW33kc532mZbYxIQxo4B4sJOVG7pZzjkxxVf7XeMQclLCiQxVnVQ-O7QuSvh3f7ntVEMnUPsHv8faccktd5_ffymV7hqgFunhyhNL74-dVvg-xa8qQEWA0NPUPL7xSmWYuvo-MFDFI29cWz1g-LCzBnzgUyA' -H 'code_verifier: 68c3p0LRIpRZjeeBaASComn8mRlXV6eZIvhwBWZoAkvWqmvbH-J928T7A-P1WvuzTsR7T2GPorCdHwzKtmfdsX0YnWJP9qSdihtSJpVZ6JukeDiYnHBK4b88amZl1eZN'

Response: 400Bad Request Time stamp: Fri, 16 Sep 2022 13:56:41 GMT
{
    "error": "invalid_request"
}

**Comment by CDR-DF** [comment]
Hi @gvharibb,

When making a call to the token endpoint, the parameters should be passed as Form Serialized parameters.  In your example above, you are passing the parameters as HTTP Header values (e.g. -H grant_type:....).

Instead, make the call like below:

```
curl -L -X POST 'https://dh-bank.secure.idp.cdrsandbox.gov.au/connect/token'
   -H "Content-Type: application/x-www-form-urlencoded" 
   -d "grant_type=authorization_code&client_id=246df974-dbc6-4d9d-9ac1-49253d51fe73&....etc...." 
```

As per: [https://openid.net/specs/openid-connect-core-1_0.html#TokenEndpoint](https://openid.net/specs/openid-connect-core-1_0.html#TokenEndpoint)

**Comment by psharma211** [comment]
Thanks for the suggestion, after making the correction during token call, we are getting a different error.

Request:

curl -L -X POST '[https://dh-bank.secure.idp.cdrsandbox.gov.au/connect/token'](https://dh-bank.secure.idp.cdrsandbox.gov.au/connect/token%27) -H 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=authorization_code' --data-urlencode 'code=3824160E72AFF115E663126899FCB55FF74B1E3A0ECA1C7FD6B1C704E474FA1E' --data-urlencode 'client_id=246df974-dbc6-4d9d-9ac1-49253d51fe73' --data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' --data-urlencode 'client_assertion=eyJ0eXAiOiJKV1QiLCJhbGciOiJQUzI1NiIsImtpZCI6IjE4NzI2MjQ5MzgzMTc3NzU4NjgxNzc2NTY0NjE4ODYxNTc1MzA2In0.eyJhdWQiOiJodHRwczovL2RoLWJhbmsuc2VjdXJlLmlkcC5jZHJzYW5kYm94Lmdvdi5hdS9jb25uZWN0L3Rva2VuIiwiaXNzIjoiMjQ2ZGY5NzQtZGJjNi00ZDlkLTlhYzEtNDkyNTNkNTFmZTczIiwic3ViIjoiMjQ2ZGY5NzQtZGJjNi00ZDlkLTlhYzEtNDkyNTNkNTFmZTczIiwianRpIjoiMjM0ZjgwZWQtNjA0ZC00NTZjLWJkYzQtZDAwZDgyYjUxMzc5IiwiZXhwIjoxNjYzNTg3NDU0LCJpYXQiOjE2NjM1ODM4NTR9.qxgZzc8k88A24cJZUbLI_fMss0mQu11y3e03ab1xl8ltWLrvgUedhur-nhuYgj2KJlIJI8hbnAXagOSWeFUZh0dnGtz2_HgdR7vsCvEBb-n1iJS4TVlFRTKEwFWH-FYJ-ZVLZfArU_AwD_wWFfCf_v0ZnEz-ZOOtvukZz2yxxHYTwehglu3xUN17NuCx-vSfKqX_taYfnb16yyXlq3VXCJJfUceFoUN55_qR6K02aNsg701CW0fYhQTp6nia-9TfiO7KIneCx1Eg-1BsvvKYQ7ijs4s5H30I9YRekEdQqoBJIttkBBlJniSqothzpNcURPhvDZUF5NxxsJyV14LUrQ' --data-urlencode 'code_verifier=zutL1jTJO3IXUxK_a5y4RcgVVNV8For8nIlTAZYvwZwtWtcH9-DbF1hb4OMV1Vzrq2LR'



Response:
{
    "error": "unauthorized_client"
}



400 Bad Request

**Comment by CDR-DF** [comment]
Hi @gvharibb,

The next issue we are seeing is: "Redirect URI is missing".

Please add the redirect_uri parameter to the token request and try again.

**Comment by psharma211** [comment]
Hi @CDR-DavidR We stuck is uploading the leaf certs to our environment. When we are trying to upload the transport leaf certificate, we are getting the following exception "Illegal base64 character 2d". Please let us know what is the encoding format that you have used on your side.

**Comment by CDR-DF** [comment]
Hi @psharma211,

Can you please let me know where you are trying to upload the certificate to?  Is this a certificate that you have downloaded from the Sandbox Portal?

**Comment by psharma211** [comment]
Hi @CDR-DF  please ignore it we are able to use the certs in our environment. Yes these are the certs downloaded from sandbox portal.

**Comment by CDR-AndrewG** [comment]
Hi @psharma211,

I believe this issue has been resolved and can be closed now. Please reach out if you are having any more issues.
