### ISSUE TITLE
Dynamic Client Registration for EnergyAustralia (EnergyAustralia-AZ (2f201dc2-3996-4642-8ac9-a1147a0bf55b)status is failed in Sandbox 

### ISSUE THREAD

**Issue by VinayakEA** [ConsumerDataRight/sandbox#9]
**Describe the bug**
**Dynamic Client Registrations, EnergyAustralia brand current status "DCRFailed"**

**To Reproduce**
1.  Login to sandbox
2. Click Dynamic Client Registrations option
3. Check the DH brand = EnergyAustralia-AZ (2f201dc2-3996-4642-8ac9-a1147a0bf55b)
4. Verify the status

**Expected behaviour**
**DCR status should be "DCRComplete" instead of "DCRfailed"**

**Screenshots**
Attached Screenshot

**Additional context**
Please fix this issue for DH brand = EnergyAustralia-AZ (2f201dc2-3996-4642-8ac9-a1147a0bf55b) so we can test the consent flow.

**Comment by VinayakEA** [comment]
![Uploading DCRfailed.png…]()

**Comment by VinayakEA** [comment]
Hi Team,
Please find the attached detailed screenshot where we created legal entities and when tried to create Data holder brand for EA, then DCR is failed, Please check and advise as it is blocking our testing
[ACCC Sandbox - EA DCR Failed.docx](https://github.com/ConsumerDataRight/sandbox/files/9571688/ACCC.Sandbox.-.EA.DCR.Failed.docx)

**Comment by CDR-AndrewG** [comment]
Hi @VinayakEA,

Thank you for getting in touch to raise this issue.

We are seeing a `401 Unauthorised error. Invalid client certificate` returned when attempting DCR with the Energy Australia Data Holder. 

It could be a certificate issue. Have the [sandbox certificates](https://consumerdataright.atlassian.net/wiki/spaces/PT/pages/5013568/Root+and+Intermediate+Certificate+Authorities) been added for your Data Holder solution?

If that doe not help, Dynamic Client Registration is re-attempted every five minutes, are there any issues you can see from your end?

**Comment by VinayakEA** [comment]
Thanks @CDR-AndrewG ,  I have informed internal team to check the sandbox certificate again and will keep you posted. Thanks for your reply.

**Comment by VinayakEA** [comment]
Hi @CDR-AndrewG We have added required certificates and tried creating DCR but it is again failed. Please find the DCR failed with today's date, can you please check what is the issue now
<img width="911" alt="Screen Shot 2022-09-16 at 9 55 47 am" src="https://user-images.githubusercontent.com/113506088/190528393-1dfa9e9b-6de8-4de7-a06a-994e8af71de4.png">

**Comment by CDR-AndrewG** [comment]
Hi @VinayakEA,

The error is the same, `401 Unauthorised error. Invalid client certificate`. Is it possible to look at what part of the DCR request the Sandbox Data Recipient is sending you is causing the unauthorised error?

**Comment by Aiden-Ziegelaar** [comment]
Full certificate chain was required in our infosec server provider, this can be closed as the EA clients are now succeeding DCR

**Comment by CDR-AndrewG** [comment]
Hi @Aiden-Ziegelaar,

Thank you for the response. We have updated our [certificate documentation](https://consumerdataright.atlassian.net/wiki/spaces/PT/pages/5013568/Root+and+Intermediate+Certificate+Authorities) to include the full certificate bundle.
